namespace VisualCrossingDataGrabber.Services
{
    internal static class Locations
    {
        public static string[] All = new string[] {
            // -------------------------------------
            // FRANCE
            // -------------------------------------
            "agde, france",
            "aix-en-provence, france",
            "ajaccio, france",
            "albi, france",
            "aléria, france",
            "amiens, france",
            "agen, france",
            "angers, france",
            "annecy, france",
            "antibes, france",
            "argenteuil, france",
            "arras, france",
            "aurillac, france",
            "auxerre, france",
            "avignon, france",
            "bayonne, france",
            "bergerac, france",
            "belfort, france",
            "besançon, france",
            "béziers, france",
            "biarritz, france",
            "biguglia, france",
            "blois, france",
            "bonifacio, france",
            "bordeau, france",
            "bordeaux, france",
            "bretigny-sur-orge, france",
            "bourges, france",
            "brest, france",
            "briançon, france",
            "brive-la-gaillarde, france",
            "caen, france",
            "calais, france",
            "cannes, france",
            "capbreton, france",
            "castres, france",
            "chalon-sur-saône, france",
            "chambéry, france",
            "champagnole, france",
            "châteauroux, france",
            "clermont-ferrand, france",
            "colmar, france",
            "courchevel, france",
            "créteil, france",
            "dax, france",
            "dourdan, france",
            "draguignan, france",
            "étampes, france",
            "foix, france",
            "forbach, france",
            "digoin, france",
            "dijon, france",
            "dunkerque, france",
            "fort-de-france, france",
            "gap, france",
            "grenoble, france",
            "isola, france",
            "l'île-rousse, france",
            "la rochelle, france",
            "laruns, france",
            "le havre, france",
            "le mans , france",
            "le puy-en-vela, france", // le puy-en-velay avec un y
            "lembach, france",
            "les abymes, france",
            "les deux alpes, france",
            "les menuires, france",
            "les Sables-d'Olonne, france",
            "lille, france",
            "limoges, france",
            "lons-le-saunier, france",
            "lourdes, france",
            "lyon, france",
            "mâcon, france",
            "marseille, france",
            "mérignac, france",
            "metz, france",
            "millau, france",
            "mimizan, france",
            "mont-de-marsan, france",
            "montélimar, france",
            "montpellier, france",
            "mouthe, france",
            "moutier, france",
            "mulhouse, france",
            "nancy, france",
            "nantes, france",
            "narbonne, france",
            "nevers, france",
            "nice, france",
            "nîmes, france",
            "nouméa, france",
            "orleans, france",
            "paray-le-monial, france",
            "paris, france",
            "pau, france",
            "périgueux, france",
            "perpignan, france",
            "poitiers, france",
            "pontarlier, france",
            "porto-vecchio, france",
            "propriano, france",
            "quimper, france",
            "reins, france",
            "rennes, france",
            "roanne, france",
            "roubaix, france",
            "rouen, france",
            "saint-dizier, france",
            "saint-claude, france",
            "saint-étienne, france",
            "saint-jean-de-maurienne, france",
            "saint-malo, france",
            "saint-nazaire, france",
            "saint-pierre, france",
            "saint-tropez, france",
            "strasbourg, france",
            "tignes, france",
            "toulon, france",
            "toulouse, france",
            "tourcoing, france",
            "tournus, france",
            "tours, france",
            "troyes, france",
            "val thorens, france",
            "valence, france",
            "vars, france",
            "versailles, france",
            "vichy, france",
            // -------------------------------------
            // ESPAGNE
            // -------------------------------------
            "albacete, espagne",
            "alcalá de henares, espagne",
            "alcorcón, espagne",
            "alicante, espagne",
            "almeria, espagne",
            "almeria, espagne",
            "avila, espagne",
            "badajoz, espagne",
            "badalone, espagne",
            "barcelone, espagne",
            "bilbao, espagne",
            "burgos, espagne",
            "caceres, espagne",
            "cadix, espagne",
            "carthagène, espagne",
            "castellon, espagne",
            "castellón de la plana, espagne",
            "ciudad real, espagne",
            "cordoue, espagne",
            "cuenca, espagne",
            "elche, espagne",
            "fuenlabrada, espagne",
            "getafe, espagne",
            "gijón, espagne",
            "grenade, espagne",
            "guadalajara, espagne",
            "huelva, espagne",
            "huesca, espagne",
            "jaen, espagne",
            "jerez de la frontera, espagne",
            "l'hospitalet de llobregat, espagne",
            "la corogne, espagne",
            "las palmas de gran canaria, espagne",
            "leganés, espagne",
            "leon, espagne",
            "logroño, espagne",
            "lugo, espagne",
            "léon, espagne",
            "lérida, espagne",
            "madrid, espagne",
            "malaga, espagne",
            "murcie, espagne",
            "móstoles, espagne",
            "orense, espagne",
            "oviedo, espagne",
            "palma de majorque, espagne",
            "pampelune, espagne",
            "pontevedra, espagne",
            "sabadell, espagne",
            "saint-sébastien, espagne",
            "salamanque, espagne",
            "santa cruz de tenerife, espagne",
            "santander, espagne",
            "saragosse, espagne",
            "segovie, espagne",
            "soria, espagne",
            "séville, espagne",
            "tarragone, espagne",
            "terrassa, espagne",
            "tolede, espagne",
            "valence, espagne",
            "valladolid, espagne",
            "vigo, espagne",
            "vitoria-gasteiz, espagne",
            "zamora, espagne",
            // -------------------------------------
            // ITALIE
            // -------------------------------------
            "ancone, italie",
            "arezzo, italie",
            "asti, italie",
            "bari, italie",
            "benevento, italie",
            "bergame, italie",
            "bologne, italie",
            "bolzane, italie",
            "brescia, italie",
            "brindisi, italie",
            "cagliari, italie",
            "campobasso, italie",
            "caserte, italie",
            "catane, italie",
            "catanzaro, italie",
            "chieti, italie",
            "cosenza, italie",
            "cremona, italie",
            "côme, italie",
            "ferrare, italie",
            "florence, italie",
            "foggia, italie",
            "forlì, italie",
            "frosinone, italie",
            "giugliano in campania, italie",
            "grosseto, italie",
            "gênes, italie",
            "l'aquila, italie",
            "la spezia, italie",
            "latina, italie",
            "lecce, italie",
            "livourne, italie",
            "lodi, italie",
            "lucca, italie",
            "massa, italie",
            "matera, italie",
            "messine, italie",
            "milan, italie",
            "modène, italie",
            "monza, italie",
            "naples, italie",
            "novare, italie",
            "olbia, italie",
            "oristano, italie",
            "padoue, italie",
            "palermo, italie",
            "parme, italie",
            "pavia, italie",
            "pescara, italie",
            "piacenza, italie",
            "pise, italie",
            "plaisance, italie",
            "potenza, italie",
            "prato, italie",
            "pérouse, italie",
            "ravenna, italie",
            "ravenne, italie",
            "reggio d'émilie, italie",
            "reggio de calabre, italie",
            "rieti, italie",
            "rimini, italie",
            "rome, italie",
            "saint-marin, italie",
            "salerne, italie",
            "sassari, italie",
            "sienne, italie",
            "siracusa, italie",
            "sondrio, italie",
            "syracuse, italie",
            "taranto, italie",
            "tarente, italie",
            "terni, italie",
            "trente, italie",
            "trieste, italie",
            "turin, italie",
            "udine, italie",
            "varese, italie",
            "venezia, italie",
            "venise, italie",
            "vercelli, italie",
            "vicence, italie",
            "viterbo, italie",
            "vérone, italie",
            // -------------------------------------
            // ALLEMAGNE
            // -------------------------------------
            "aix-la-chapelle, allemagne",
            "augsbourg, allemagne",
            "bayreuth, allemagne",
            "berlin, allemagne",
            "bielefeld, allemagne",
            "bochum, allemagne",
            "bonn, allemagne",
            "bremen, allemagne",
            "brunswick, allemagne",
            "brême, allemagne",
            "cassel, allemagne",
            "chemnitz, allemagne",
            "cobourg, allemagne",
            "cologne, allemagne",
            "constance, allemagne",
            "cottbus, allemagne",
            "darmstadt, allemagne",
            "dortmund, allemagne",
            "dresde, allemagne",
            "duisbourg, allemagne",
            "düsseldorf, allemagne",
            "erfurt, allemagne",
            "essen, allemagne",
            "flensbourg, allemagne",
            "francfort, allemagne",
            "freiburg, allemagne",
            "fribourg-en-brisgau, allemagne",
            "gelsenkirchen, allemagne",
            "gotha, allemagne",
            "hagen, allemagne",
            "halle, allemagne",
            "hambourg, allemagne",
            "hamm, allemagne",
            "hanovre, allemagne",
            "heidelberg, allemagne",
            "heilbronn, allemagne",
            "ingolstadt, allemagne",
            "jena, allemagne",
            "kaiserslautern, allemagne",
            "karlsruhe, allemagne",
            "kiel, allemagne",
            "krefeld, allemagne",
            "leipzig, allemagne",
            "leverkusen, allemagne",
            "ludwigshafen, allemagne",
            "lübeck, allemagne",
            "magdebourg, allemagne",
            "mannheim, allemagne",
            "mayence, allemagne",
            "munich, allemagne",
            "mönchengladbach, allemagne",
            "mülheim, allemagne",
            "münster, allemagne",
            "nuremberg, allemagne",
            "oberhausen, allemagne",
            "offenbach, allemagne",
            "oldenbourg, allemagne",
            "osnabrück, allemagne",
            "passau, allemagne",
            "potsdam, allemagne",
            "regensburg, allemagne",
            "reutlingen, allemagne",
            "rostock, allemagne",
            "sarrebruck, allemagne",
            "schwerin, allemagne",
            "siegen, allemagne",
            "stuttgart, allemagne",
            "trier, allemagne",
            "ulm, allemagne",
            "weimar, allemagne",
            "wiesbaden, allemagne",
            "wolfsburg, allemagne",
            "worms, allemagne",
            "wuppertal, allemagne",
            "zwickau, allemagne",
            // -------------------------------------
            // SUISSE
            // -------------------------------------
            "aigle, suisse",
            "bellinzone, suisse",
            "berne, suisse",
            "bienne, suisse",
            "bâle, suisse",
            "chur, suisse",
            "davos, suisse",
            "delémont, suisse",
            "frauenfeld, suisse",
            "fribourg, suisse",
            "genève, suisse",
            "glaris, suisse",
            "granges, suisse",
            "interlaken, suisse",
            "köniz, suisse",
            "lausanne, suisse",
            "locarno, suisse",
            "lucerne, suisse",
            "lugano, suisse",
            "martigny, suisse",
            "montreux, suisse",
            "morat, suisse",
            "neuchâtel, suisse",
            "olten, suisse",
            "saint-gall, suisse",
            "schaffhouse, suisse",
            "sion, suisse",
            "soleure, suisse",
            "uster, suisse",
            "vevey, suisse",
            "yverdon-les-bains, suisse",
            "zoug, suisse",
            "zurich, suisse",
            // -------------------------------------
            // BELGIQUE
            // -------------------------------------
            "alost, belgique",
            "anderlecht, belgique",
            "anvers, belgique",
            "arlon, belgique",
            "bruges, belgique",
            "bruxelles, belgique",
            "charleroi, belgique",
            "courtrai, belgique",
            "dinant, belgique",
            "gand, belgique",
            "genk, belgique",
            "hasselt, belgique",
            "herstal, belgique",
            "ixelles, belgique",
            "la louvière, belgique",
            "laeken, belgique",
            "leuven, belgique",
            "liège, belgique",
            "louvain, belgique",
            "malines, belgique",
            "molenbeek-saint-jean, belgique",
            "mons, belgique",
            "namur, belgique",
            "nivelles, belgique",
            "ostende, belgique",
            "roeselare, belgique",
            "saint-nicolas, belgique",
            "schaerbeek, belgique",
            "seraing, belgique",
            "tournai, belgique",
            "uccle, belgique",
            "verviers, belgique",
            "villers-la-ville, belgique",
            "waregem, belgique",
            "wavre, belgique",
            "yprès, belgique",
            "zaventem, belgique",
            // -------------------------------------
            // USA 
            // -------------------------------------
            "albuquerque, usa",
            "anchorage, usa",
            "arlington, usa",
            "atlanta, usa",
            "aurora, usa",
            "austin, usa",
            "bakersfield, usa",
            "baltimore, usa",
            "birmingham, usa",
            "boise, usa",
            "boston, usa",
            "buffalo, usa",
            "charlotte, usa",
            "chattanooga, usa",
            "chicago, usa",
            "cleveland, usa",
            "colorado springs, usa",
            "columbus, usa",
            "corpus christi, usa",
            "dallas, usa",
            "daytona beach, usa",
            "denver, usa",
            "des moines, usa",
            "détroit, usa",
            "el paso, usa",
            "fargo, usa",
            "fort lauderdale, usa",
            "fort worth, usa",
            "fresno, usa",
            "grand rapids, usa",
            "green bay, usa",
            "honolulu, usa",
            "houston, usa",
            "indianapolis, usa",
            "jacksonville, usa",
            "kansas city, usa",
            "knoxville, usa",
            "la nouvelle-orléans, usa",
            "las vegas, usa",
            "lincoln, usa",
            "long beach, usa",
            "los angeles, usa",
            "louisville, usa",
            "lubbock, usa",
            "madison, usa",
            "memphis, usa",
            "mesa, usa",
            "miami, usa",
            "milwaukee, usa",
            "minneapolis, usa",
            "mobile, usa",
            "nashville, usa",
            "new york, usa",
            "oakland, usa",
            "oklahoma city, usa",
            "omaha, usa",
            "orlando, usa",
            "philadelphie, usa",
            "phoenix, usa",
            "pittsburgh, usa",
            "portland, usa",
            "raleigh, usa",
            "reno, usa",
            "richmond, usa",
            "rochester, usa",
            "sacramento, usa",
            "saint louis, usa",
            "salt lake city, usa",
            "san antonio, usa",
            "san diego, usa",
            "san francisco, usa",
            "san josé, usa",
            "sarasota, usa",
            "seattle, usa",
            "spokane, usa",
            "springfield, usa",
            "syracuse, usa",
            "tampa, usa",
            "tucson, usa",
            "tulsa, usa",
            "virginia beach, usa",
            "washington DC, usa",
            "wichita, usa",
            // -------------------------------------
            // Bresil 
            // -------------------------------------
            "anápolis, brésil",
            "aracaju, brésil",
            "belo horizonte, brésil",
            "belém, brésil",
            "betim, brésil",
            "brasília, brésil",
            "campinas, brésil",
            "campo grande, brésil",
            "contagem, brésil",
            "curitiba, brésil",
            "duque de caxias, brésil",
            "feira de santana, brésil",
            "fortaleza, brésil",
            "goiânia, brésil",
            "guarulhos, brésil",
            "jaboatão dos guararapes, brésil",
            "joinville, brésil",
            "joão pessoa, brésil",
            "juiz de fora, brésil",
            "londrina, brésil",
            "maceió, brésil",
            "manaus, brésil",
            "natal, brésil",
            "niterói, brésil",
            "nova iguaçu, brésil",
            "osasco, brésil",
            "porto alegre, brésil",
            "recife, brésil",
            "ribeirão preto, brésil",
            "rio de janeiro, brésil",
            "salvador da bahia, brésil",
            "santo andré, brésil",
            "sorocaba, brésil",
            "são bernardo do campo, brésil",
            "são gonçalo, brésil",
            "são josé dos campos, brésil",
            "são luís, brésil",
            "são paulo, brésil",
            "teresina, brésil",
            "uberlândia, brésil",
            // -------------------------------------
            // Japon
            // -------------------------------------
            "akita, japon",
            "chiba, japon",
            "fukuoka, japon",
            "funabashi, japon",
            "hamamatsu, japon",
            "himeji, japon",
            "hiroshima, japon",
            "kagoshima, japon",
            "kanazawa, japon",
            "kawasaki, japon",
            "kitakyūshū, japon",
            "koriyama, japon",
            "kumamoto, japon",
            "kyōto, japon",
            "kōbe, japon",
            "kōchi, japon",
            "matsumoto, japon",
            "miyazaki, japon",
            "nagasaki, japon",
            "nagoya, japon",
            "naha, japon",
            "nara, japon",
            "niigata, japon",
            "ochiai, japon",
            "okayama, japon",
            "saitama, japon",
            "sakai, japon",
            "sapporo, japon",
            "sendai, japon",
            "shizuoka, japon",
            "takamatsu, japon",
            "tokyo, japon",
            "toyama, japon",
            "utsunomiya, japon",
            "wakayama, japon",
            "yamagata, japon",
            "yokohama, japon",
            "ōsaka, japon",
            // -------------------------------------
            // Australie
            // -------------------------------------
            "adélaïde, australie",
            "albury, australie",
            "ballarat, australie",
            "bathurst, australie",
            "bendigo, australie",
            "brisbane, australie",
            "bunbury, australie",
            "bundaberg, australie",
            "cairns, australie",
            "canberra, australie",
            "coffs harbour, australie",
            "darwin, australie",
            "dubbo, australie",
            "geelong, australie",
            "geraldton, australie",
            "gladstone, australie",
            "gold coast, australie",
            "hervey bay, australie",
            "hobart, australie",
            "kalgoorlie, australie",
            "launceston, australie",
            "mackay, australie",
            "melbourne, australie",
            "mildura, australie",
            "newcastle, australie",
            "orange, australie",
            "perth, australie",
            "port macquarie, australie",
            "rockhampton, australie",
            "shepparton, australie",
            "sunshine coast, australie",
            "sydney, australie",
            "tamworth, australie",
            "toowoomba, australie",
            "townsville, australie",
            "wagga wagga, australie",
            "wollongong, australie",
            // -------------------------------------
            // CANADA
            // -------------------------------------
            "abbotsford, canada",
            "ajax, canada",
            "barrie, canada",
            "brampton, canada",
            "burlington, canada",
            "burnaby, canada",
            "calgary, canada",
            "cambridge, canada",
            "coquitlam, canada",
            "delta, canada",
            "edmonton, canada",
            "gatineau, canada",
            "greater sudbury, canada",
            "guelph, canada",
            "halifax, canada",
            "hamilton, canada",
            "kelowna, canada",
            "kingston, canada",
            "kitchener, canada",
            "langley, canada",
            "laval, canada",
            "london, canada",
            "longueuil, canada",
            "lévis, canada",
            "markham, canada",
            "milton, canada",
            "mississauga, canada",
            "montréal, canada",
            "oakville, canada",
            "oshawa, canada",
            "ottawa, canada",
            "québec, canada",
            "regina, canada",
            "richmond hill, canada",
            "richmond, canada",
            "saanich, canada",
            "saguenay, canada",
            "saskatoon, canada",
            "sherbrooke, canada",
            "st. catharines, canada",
            "st. john's, canada",
            "surrey, canada",
            "terrebonne, canada",
            "thunder bay, canada",
            "toronto, canada",
            "trois-rivières, canada",
            "vancouver, canada",
            "vaughan, canada",
            "waterloo, canada",
            "whitby, canada",
            "winnipeg, canada",
            // -------------------------------------
            // POLOGNE
            // -------------------------------------
            "białystok, pologne",
            "bielsko-biała, pologne",
            "bydgoszcz, pologne",
            "bytom, pologne",
            "chorzów, pologne",
            "cracovie, pologne",
            "częstochowa, pologne",
            "elbląg, pologne",
            "gdańsk, pologne",
            "gdynia, pologne",
            "gliwice, pologne",
            "jelenia góra, pologne",
            "kalisz, pologne",
            "katowice, pologne",
            "kielce, pologne",
            "koszalin, pologne",
            "legnica, pologne",
            "lublin, pologne",
            "malbork, pologne",
            "nowy sącz, pologne",
            "olsztyn, pologne",
            "opole, pologne",
            "poznań, pologne",
            "płock, pologne",
            "radom, pologne",
            "ruda śląska, pologne",
            "rybnik, pologne",
            "rzeszów, pologne",
            "sosnowiec, pologne",
            "szczecin, pologne",
            "tarnów, pologne",
            "toruń, pologne",
            "varsovie, pologne",
            "wrocław, pologne",
            "zabrze, pologne",
            "zielona góra, pologne",
            "łódź, pologne",
            "śląsk, pologne",
            // -------------------------------------
            // AFRIQUE DU SUD
            // -------------------------------------
            "benoni, afrique du sud",
            "bloemfontein, afrique du sud",
            "boksburg, afrique du sud",
            "durban, afrique du sud",
            "east london, afrique du sud",
            "george, afrique du sud",
            "grahamstown, afrique du sud",
            "johannesburg, afrique du sud",
            "kimberley, afrique du sud",
            "knysna, afrique du sud",
            "krugersdorp, afrique du sud",
            "le cap, afrique du sud",
            "mahikeng, afrique du sud",
            "nelspruit, afrique du sud",
            "oudtshoorn, afrique du sud",
            "paarl, afrique du sud",
            "pietermaritzburg, afrique du sud",
            "polokwane, afrique du sud",
            "port elizabeth, afrique du sud",
            "pretoria, afrique du sud",
            "randburg, afrique du sud",
            "rustenburg, afrique du sud",
            "soweto, afrique du sud",
            "springs, afrique du sud",
            "stellenbosch, afrique du sud",
            "tembisa, afrique du sud",
            "ulundi, afrique du sud",
            "upington, afrique du sud",
            "vereeniging, afrique du sud",
            "welkom, afrique du sud",
            // -------------------------------------
            // NORVEGE 
            // -------------------------------------
            "arendal, norvège",
            "askøy, norvège",
            "bergen, norvège",
            "bodø, norvège",
            "drammen, norvège",
            "fredrikstad, norvège",
            "gjøvik, norvège",
            "halden, norvège",
            "hamar, norvège",
            "harstad, norvège",
            "haugesund, norvège",
            "horten, norvège",
            "kongsberg, norvège",
            "kristiansand, norvège",
            "kristiansund, norvège",
            "larvik, norvège",
            "lillehammer, norvège",
            "mo i rana, norvège",
            "molde, norvège",
            "moss, norvège",
            "oslo, norvège",
            "porsgrunn, norvège",
            "sandefjord, norvège",
            "sandvika, norvège",
            "sarpsborg, norvège",
            "skien, norvège",
            "stavanger, norvège",
            "tromsø, norvège",
            "trondheim, norvège",
            "tønsberg, norvège",
            "ålesund, norvège",
            // -------------------------------------
            // SINGAPOUR ; 
            // -------------------------------------
            "singapour, singapour",
            // -------------------------------------
            // HAWAÏ ; 
            // -------------------------------------
            "hilo, hawaï",
            "honolulu, hawaï",
            "kahului, maui",
            "kailua-kona, hawaï",
            "lahaina, maui",
            "lihue, kauai",
            "waimea, kauai",
            // -------------------------------------
            // MEXIQUE ; 
            // -------------------------------------
            "aguascalientes, mexique",
            "chihuahua, mexique",
            "ciudad victoria, mexique",
            "culiacán, mexique",
            "durango, mexique",
            "ecatepec, mexique",
            "guadalajara, mexique",
            "guadalupe, mexique",
            "hermosillo, mexique",
            "irapuato, mexique",
            "juárez, mexique",
            "león, mexique",
            "mexicali, mexique",
            "mexico, mexique",
            "monterrey, mexique",
            "morelia, mexique",
            "mérida, mexique",
            "naucalpan, mexique",
            "nezahualcóyotl, mexique",
            "puebla, mexique",
            "querétaro, mexique",
            "reynosa, mexique",
            "saltillo, mexique",
            "san luis potosí, mexique",
            "tijuana, mexique",
            "tlalnepantla, mexique",
            "tlaquepaque, mexique",
            "torreón, mexique",
            "tuxtla gutiérrez, mexique",
            "tuxtla, mexique",
            "veracruz, mexique",
            "villahermosa, mexique",
            "xalapa, mexique",
            "zapopan, mexique",
            // -------------------------------------
            // COLOMBIE ; 
            // -------------------------------------
            "armenia, colombie",
            "barranquilla, colombie",
            "bello, colombie",
            "bogota, colombie",
            "bucaramanga, colombie",
            "buenaventura, colombie",
            "cali, colombie",
            "cartagena, colombie",
            "cartago, colombie",
            "cúcuta, colombie",
            "dosquebradas, colombie",
            "envigado, colombie",
            "floridablanca, colombie",
            "ibagué, colombie",
            "manizales, colombie",
            "medellín, colombie",
            "montería, colombie",
            "neiva, colombie",
            "palmira, colombie",
            "pasto, colombie",
            "pereira, colombie",
            "popayán, colombie",
            "santa marta, colombie",
            "sincelejo, colombie",
            "soacha, colombie",
            "soledad, colombie",
            "tulúa, colombie",
            "valledupar, colombie",
            "villavicencio, colombie",
            // -------------------------------------
            // ARGENTINE
            // -------------------------------------
            "bahía blanca, argentine",
            "buenos aires, argentine",
            "catamarca, argentine",
            "corrientes, argentine",
            "córdoba, argentine",
            "formosa, argentine",
            "la plata, argentine",
            "la rioja, argentine",
            "mar del plata, argentine",
            "mendoza, argentine",
            "neuquén, argentine",
            "paraná, argentine",
            "posadas, argentine",
            "rawson, argentine",
            "resistencia, argentine",
            "rosario, argentine",
            "río gallegos, argentine",
            "salta, argentine",
            "san juan, argentine",
            "san luis, argentine",
            "san miguel de tucumán, argentine",
            "san salvador de jujuy, argentine",
            "santa fe, argentine",
            "santiago del estero, argentine",
            "tucumán, argentine",
            "ushuaia, argentine",
            // -------------------------------------
            // ALGERIE
            // -------------------------------------
            "ain defla, algérie",
            "alger, algérie",
            "annaba, algérie",
            "batna, algérie",
            "biskra, algérie",
            "bjelfa, algérie",
            "blida, algérie",
            "bordj bou arreridj, algérie",
            "béjaïa, algérie",
            "chlef, algérie",
            "constantine, algérie",
            "el eulma, algérie",
            "el oued, algérie",
            "guelma, algérie",
            "jijel, algérie",
            "khénchela, algérie",
            "laghouat, algérie",
            "mascara, algérie",
            "mostaganem, algérie",
            "médéa, algérie",
            "oran, algérie",
            "ouargla, algérie",
            "sidi bel abbès, algérie",
            "skikda, algérie",
            "souk ahras, algérie",
            "sétif, algérie",
            "tiaret, algérie",
            "tizi ouzou, algérie",
            "tlemcen, algérie",
            "tébessa, algérie",
            // -------------------------------------
            // MAROC 
            // -------------------------------------
            "agadir, maroc",
            "al hoceima, maroc",
            "beni mellal, maroc",
            "berrechid, maroc",
            "bouskoura, maroc",
            "casablanca, maroc",
            "dakhla, maroc",
            "el jadida, maroc",
            "errachidia, maroc",
            "essaouira, maroc",
            "fès, maroc",
            "guelmim, maroc",
            "kenitra, maroc",
            "khouribga, maroc",
            "khémisset, maroc",
            "larache, maroc",
            "marrakech, maroc",
            "martil, maroc",
            "meknès, maroc",
            "ouarzazate, maroc",
            "oujda, maroc",
            "rabat, maroc",
            "safi, maroc",
            "salé, maroc",
            "settat, maroc",
            "tanger, maroc",
            "taourirt, maroc",
            "tetouan, maroc",
            "tiznit, maroc",
            "témara, maroc",
            // -------------------------------------
            // ARABIE SAOUDITE
            // -------------------------------------
            "abha, arabie saoudite",
            "al hufuf, arabie saoudite",
            "al khobar, arabie saoudite",
            "al mubarraz, arabie saoudite",
            "al qatif, arabie saoudite",
            "dammam, arabie saoudite",
            "djeddah, arabie saoudite",
            "ha'il, arabie saoudite",
            "jizan, arabie saoudite",
            "jubail, arabie saoudite",
            "khobar, arabie saoudite",
            "la mecque, arabie saoudite",
            "médine, arabie saoudite",
            "najran, arabie saoudite",
            "riyad, arabie saoudite",
            "ta'if, arabie saoudite",
            "tabuk, arabie saoudite",
            "yanbu, arabie saoudite",
            // -------------------------------------
            // CHINE 
            // -------------------------------------
            "baoji, chine",
            "bengbu, chine",
            "benxi, chine",
            "changchun, chine",
            "changsha, chine",
            "changzhou, chine",
            "chengdu, chine",
            "chifeng, chine",
            "chongqing, chine",
            "dalian, chine",
            "dandong, chine",
            "daqing, chine",
            "datong, chine",
            "dongguan, chine",
            "ezhou, chine",
            "foshan, chine",
            "fuxin, chine",
            "fuzhou, chine",
            "gongzhuling, chine",
            "guangzhou, chine",
            "guilin, chine",
            "guiyang, chine",
            "haikou, chine",
            "handan, chine",
            "hangzhou, chine",
            "harbin, chine",
            "hefei, chine",
            "hengyang, chine",
            "hohhot, chine",
            "huaibei, chine",
            "huainan, chine",
            "humen, chine",
            "huzhou, chine",
            "jiamusi, chine",
            "jilin, chine",
            "jinan, chine",
            "jingzhou, chine",
            "jining, chine",
            "jixi, chine",
            "kaifeng, chine",
            "kunming, chine",
            "lanzhou, chine",
            "leshan, chine",
            "liaoyang, chine",
            "luoyang, chine",
            "nanchang, chine",
            "nanchong, chine",
            "nanjing, chine",
            "nanning, chine",
            "nanyang, chine",
            "ningbo, chine",
            "pékin, chine",
            "pingdingshan, chine",
            "qingdao, chine",
            "qiqihar, chine",
            "shanghai, chine",
            "shantou, chine",
            "shenyang, chine",
            "shenzhen, chine",
            "shijiazhuang, chine",
            "suzhou, chine",
            "tai'an, chine",
            "taiyuan, chine",
            "tangshan, chine",
            "tianjin, chine",
            "urumqi, chine",
            "weifang, chine",
            "wuhan, chine",
            "wuhu, chine",
            "wuxi, chine",
            "xiamen, chine",
            "xi'an, chine",
            "xiangfan, chine",
            "xinxiang, chine",
            "xining, chine",
            "yangzhou, chine",
            "yantai, chine",
            "yichang, chine",
            "yichun, chine",
            "yinchuan, chine",
            "yingkou, chine",
            "yueyang, chine",
            "zaozhuang, chine",
            "zhangjiakou, chine",
            "zhanjiang, chine",
            "zhengzhou, chine",
            // -------------------------------------
            // INDE
            // -------------------------------------
            "agra, inde",
            "ahmedabad, inde",
            "allahabad, inde",
            "amritsar, inde",
            "bengaluru, inde",
            "bhopal, inde",
            "chandigarh, inde",
            "chennai, inde",
            "coimbatore, inde",
            "delhi, inde",
            "dhanbad, inde",
            "faridabad, inde",
            "firozabad, inde",
            "guwahati, inde",
            "gwalior, inde",
            "hyderabad, inde",
            "indore, inde",
            "jabalpur, inde",
            "jaipur, inde",
            "jodhpur, inde",
            "kanpur, inde",
            "kolkata, inde",
            "lucknow, inde",
            "ludhiana, inde",
            "madurai, inde",
            "meerut, inde",
            "mumbai, inde",
            "nagpur, inde",
            "nashik, inde",
            "patna, inde",
            "pune, inde",
            "raipur, inde",
            "rajpur sonarpur, inde",
            "srinagar, inde",
            "surat, inde",
            "thane, inde",
            "vadodara, inde",
            "varanasi, inde",
            "vijayawada, inde",
            "visakhapatnam, inde",
            // -------------------------------------
            // ROYAUME-UNI 
            // -------------------------------------
            "aberdeen, royaume-uni",
            "bath, royaume-uni",
            "belfast, royaume-uni",
            "birmingham, royaume-uni",
            "bradford, royaume-uni",
            "brighton, royaume-uni",
            "bristol, royaume-uni",
            "cambridge, royaume-uni",
            "cardiff, royaume-uni",
            "coventry, royaume-uni",
            "derby, royaume-uni",
            "dundee, royaume-uni",
            "exeter, royaume-uni",
            "glasgow, royaume-uni",
            "inverness, royaume-uni",
            "kingston, royaume-uni",
            "lancaster, royaume-uni",
            "leeds, royaume-uni",
            "leicester, royaume-uni",
            "liverpool, royaume-uni",
            "londres, royaume-uni",
            "manchester, royaume-uni",
            "newcastle, royaume-uni",
            "norwich, royaume-uni",
            "nottingham, royaume-uni",
            "oxford, royaume-uni",
            "peterborough, royaume-uni",
            "plymouth, royaume-uni",
            "portsmouth, royaume-uni",
            "sheffield, royaume-uni",
            "southampton, royaume-uni",
            "stoke-on-trent, royaume-uni",
            "sunderland, royaume-uni",
            "swansea, royaume-uni",
            "wolverhampton, royaume-uni",
            "york, royaume-uni",
            "édimbourg, royaume-uni",
            // -------------------------------------
            // IRLANDE 
            // -------------------------------------
            "athlone, irlande",
            "bray, irlande",
            "carlow, irlande",
            "cork, irlande",
            "drogheda, irlande",
            "dublin, irlande",
            "dundalk, irlande",
            "ennis, irlande",
            "galway, irlande",
            "kilkenny, irlande",
            "killarney, irlande",
            "letterkenny, irlande",
            "limerick, irlande",
            "naas, irlande",
            "navan, irlande",
            "sligo, irlande",
            "sword, irlande",
            "tralee, irlande",
            "waterford, irlande",
            // -------------------------------------
            // ISLANDE 
            // -------------------------------------
            "akranes, islande",
            "akureyri, islande",
            "borgarnes, islande",
            "egilsstaðir, islande",
            "garðabær, islande",
            "hafnarfjörður, islande",
            "húsavík, islande",
            "keflavík, islande",
            "kópavogur, islande",
            "mosfellsbær, islande",
            "neskaupstaður, islande",
            "reykjavik, islande",
            "sauðárkrókur, islande",
            "selfoss, islande",
            "siglufjörður, islande",
            "ísafjörður, islande",
            // -------------------------------------
            // MADAGASCAR 
            // -------------------------------------
            "ambatondrazaka, madagascar",
            "ambositra, madagascar",
            "antalaha, madagascar",
            "antananarivo, madagascar",
            "antsirabe, madagascar",
            "antsohihy, madagascar",
            "fianarantsoa, madagascar",
            "mahajanga, madagascar",
            "manakara, madagascar",
            "morondava, madagascar",
            "nosy be, madagascar",
            "sambava, madagascar",
            "tananarive, madagascar",
            "toamasina, madagascar",
            "toliara, madagascar",
            // -------------------------------------
            // PORTUGAL
            // -------------------------------------
            "agualva-cacém, portugal",
            "almada, portugal",
            "amadora, portugal",
            "aveiro, portugal",
            "barreiro, portugal",
            "braga, portugal",
            "coimbra, portugal",
            "faró, portugal",
            "funchal, portugal",
            "gondomar, portugal",
            "guimarães, portugal",
            "leiria, portugal",
            "lisbonne, portugal",
            "matosinhos, portugal",
            "oeiras, portugal",
            "ponta delgada, portugal",
            "porto, portugal",
            "quarteira, portugal",
            "rio tinto, portugal",
            "sesimbra, portugal",
            "setúbal, portugal",
            "vila nova de gaia, portugal",
            "viseu, portugal",
            "évora, portugal",
            // -------------------------------------
            // PAYS-BAS ; depuis 
            // -------------------------------------
            "'s-hertogenbosch, pays-bas",
            "almere, pays-bas",
            "amersfoort, pays-bas",
            "amsterdam, pays-bas",
            "arnhem, pays-bas",
            "breda, pays-bas",
            "deventer, pays-bas",
            "dordrecht, pays-bas",
            "eindhoven, pays-bas",
            "emmen, pays-bas",
            "enschede, pays-bas",
            "groningen, pays-bas",
            "haarlem, pays-bas",
            "la haye, pays-bas",
            "leeuwarden, pays-bas",
            "leiden, pays-bas",
            "maastricht, pays-bas",
            "nijmegen, pays-bas",
            "rotterdam, pays-bas",
            "tilburg, pays-bas",
            "utrecht, pays-bas",
            "venlo, pays-bas",
            "zaanstad, pays-bas",
            "zwolle, pays-bas",
            // -------------------------------------
            // GRECE 
            // -------------------------------------
            "agrinio, grèce",
            "alexandroupoli, grèce",
            "athènes, grèce",
            "chania, grèce",
            "giannitsa, grèce",
            "heraklion, grèce",
            "ioannina, grèce",
            "kalamata, grèce",
            "katerini, grèce",
            "kavala, grèce",
            "komotini, grèce",
            "lamia, grèce",
            "larissa, grèce",
            "mytilene, grèce",
            "patras, grèce",
            "piraeus, grèce",
            "rhodes, grèce",
            "serres, grèce",
            "thessalonique, grèce",
            "trikala, grèce",
            "veria, grèce",
            "volos, grèce",
            "xanthi, grèce",
            // -------------------------------------
            // TUNISIE ; depuis 
            // -------------------------------------
            "ariana, tunisie",
            "beja, tunisie",
            "ben arous, tunisie",
            "bizerte, tunisie",
            "gabès, tunisie",
            "gafsa, tunisie",
            "jendouba, tunisie",
            "kairouan, tunisie",
            "kasserine, tunisie",
            "kef, tunisie",
            "la manouba, tunisie",
            "mahdia, tunisie",
            "medenine, tunisie",
            "monastir, tunisie",
            "nabeul, tunisie",
            "sfax, tunisie",
            "sid bouzid, tunisie",
            "siliana, tunisie",
            "sousse, tunisie",
            "tataouine, tunisie",
            "tozeur, tunisie",
            "tunis, tunisie",
            "zaghouan, tunisie",
            "zarzis, tunisie",
            // -------------------------------------
            // MALTE
            // -------------------------------------
            "birkirkara, malte",
            "il-mosta, malte",
            "mdina, malte",
            "qormi, malte",
            "rabat, malte",
            "sliema, malte",
            "valletta, malte",
            // -------------------------------------
            // ISRAËL 
            // -------------------------------------
            "ashdod, israël",
            "ashkelon, israël",
            "beer sheva, israël",
            "beit shemesh, israël",
            "bnei brak, israël",
            "eilat, israël",
            "hadera, israël",
            "haïfa, israël",
            "holon, israël",
            "jérusalem, israël",
            "kfar saba, israël",
            "modiin-maccabim-reut, israël",
            "nazareth, israël",
            "netanya, israël",
            "petah tikva, israël",
            "ramat gan, israël",
            "rishon lezion, israël",
            "tel aviv, israël",
            // -------------------------------------
            // COREE DU SUD 
            // -------------------------------------
            "ansan, corée du sud",
            "busan, corée du sud",
            "changwon, corée du sud",
            "cheonan, corée du sud",
            "daegu, corée du sud",
            "daejeon, corée du sud",
            "gochang, corée du sud",
            "gwangju, corée du sud",
            "incheon, corée du sud",
            "jeju, corée du sud",
            "jeonju, corée du sud",
            "pohang, corée du sud",
            "seongnam, corée du sud",
            "suwon, corée du sud",
            "séoul, corée du sud",
            "ulsan, corée du sud",
            "yongin, corée du sud",
            // -------------------------------------
            // NEPAL 
            // -------------------------------------
            "bhaktapur, népal",
            "bharatpur, népal",
            "biratnagar, népal",
            "butwal, népal",
            "dhangadhi, népal",
            "dharan, népal",
            "gulariya, népal",
            "hetauda, népal",
            "itahari, népal",
            "janakpur, népal",
            "katmandou, népal",
            "lalitpur, népal",
            "nepalgunj, népal",
            "pokhara, népal",
            "sidharthanagar, népal",
            // -------------------------------------
            // RUSSIE 
            // -------------------------------------
            "astrakhan, russie",
            "barnaul, russie",
            "iekaterinbourg, russie",
            "irkoutsk, russie",
            "izhevsk, russie",
            "kazan, russie",
            "krasnodar, russie",
            "krasnoïarsk, russie",
            "moscou, russie",
            "naberejnye tchelny, russie",
            "nijni novgorod, russie",
            "novokuznetsk, russie",
            "novossibirsk, russie",
            "omsk, russie",
            "penza, russie",
            "perm, russie",
            "rostov-sur-le-don, russie",
            "ryazan, russie",
            "saint-pétersbourg, russie",
            "samara, russie",
            "saratov, russie",
            "tcheliabinsk, russie",
            "toliatti, russie",
            "tyumen, russie",
            "vladivostok, russie",
            "volgograd, russie",
            "voronej, russie",
            "yekaterinburg, russie",
            // -------------------------------------
            // TCHEQUIE
            // -------------------------------------
            "brno, tchéquie",
            "havířov, tchéquie",
            "hradec králové, tchéquie",
            "jihlava, tchéquie",
            "karlovy vary, tchéquie",
            "kroměříž, tchéquie",
            "liberec, tchéquie",
            "olomouc, tchéquie",
            "ostrava, tchéquie",
            "pardubice, tchéquie",
            "plzeň, tchéquie",
            "prague, tchéquie",
            "zlin, tchéquie",
            "ústí nad labem, tchéquie",
            "české budějovice, tchéquie",
            // -------------------------------------
            // SLOVAQUIE
            // -------------------------------------
            "banská bystrica, slovaquie",
            "bratislava, slovaquie",
            "humenné, slovaquie",
            "košice, slovaquie",
            "martin, slovaquie",
            "michalovce, slovaquie",
            "nitra, slovaquie",
            "nové zámky, slovaquie",
            "poprad, slovaquie",
            "prešov, slovaquie",
            "prievidza, slovaquie",
            "spišská nová ves, slovaquie",
            "trenčín, slovaquie",
            "trnava, slovaquie",
            "zvolen, slovaquie",
            "žilina, slovaquie",
            // -------------------------------------
            // ROUMANIE
            // -------------------------------------
            "arad, roumanie",
            "bacau, roumanie",
            "baia mare, roumanie",
            "botosani, roumanie",
            "braila, roumanie",
            "brasov, roumanie",
            "bucarest, roumanie",
            "buzau, roumanie",
            "cluj, roumanie",
            "constanta, roumanie",
            "craiova, roumanie",
            "focsani, roumanie",
            "galati, roumanie",
            "iasi, roumanie",
            "oradea, roumanie",
            "piatra neamt, roumanie",
            "pitesti, roumanie",
            "ploiesti, roumanie",
            "ramnicu valcea, roumanie",
            "satu mare, roumanie",
            "sibiu, roumanie",
            "suceava, roumanie",
            "targu mures, roumanie",
            "timisoara, roumanie",
            // -------------------------------------
            // HONGRIE
            // -------------------------------------
            "békéscsaba, hongrie",
            "budapest, hongrie",
            "debrecen, hongrie",
            "dunaújváros, hongrie",
            "eger, hongrie",
            "győr, hongrie",
            "hódmezővásárhely, hongrie",
            "kaposvár, hongrie",
            "kecskemét, hongrie",
            "miskolc, hongrie",
            "nagykanizsa, hongrie",
            "nyíregyháza, hongrie",
            "pécs, hongrie",
            "szeged, hongrie",
            "szigetszentmiklós, hongrie",
            "szolnok, hongrie",
            "szombathely, hongrie",
            "székesfehérvár, hongrie",
            "tatabánya, hongrie",
            "vasvár, hongrie",
            "vác, hongrie",
            // -------------------------------------
            // MOLDAVIE
            // -------------------------------------
            "bender, moldavie",
            "bălți, moldavie",
            "cahul, moldavie",
            "chisinau, moldavie",
            "comrat, moldavie",
            "criuleni, moldavie",
            "dubăsari, moldavie",
            "edineț, moldavie",
            "florești, moldavie",
            "hîncești, moldavie",
            "orhei, moldavie",
            "soroca, moldavie",
            "strășeni, moldavie",
            "tiraspol, moldavie",
            "ungheni, moldavie",
            "șoldănești, moldavie",
            // -------------------------------------
            // UKRAINE
            // -------------------------------------
            "dnipro, ukraine",
            "donetsk, ukraine",
            "ivanofrankivsk, ukraine",
            "kharkiv, ukraine",
            "kherson, ukraine",
            "khmelnytskyï, ukraine",
            "kiev, ukraine",
            "kropyvnytskyï, ukraine",
            "loutsk, ukraine",
            "lviv, ukraine",
            "marioupol, ukraine",
            "mykolaïv, ukraine",
            "odessa, ukraine",
            "poltava, ukraine",
            "rivne, ukraine",
            "sumy, ukraine",
            "tcherkassy, ukraine",
            "tchernihiv, ukraine",
            "tchernivtsi, ukraine",
            "vinnytsia, ukraine",
            "zaporijia, ukraine",
            "zhytomyr, ukraine",
            // -------------------------------------
            // SUEDE
            // -------------------------------------
            "borås, suede",
            "eskilstuna, suede",
            "gävle, suede",
            "göteborg, suede",
            "halmstad, suede",
            "helsingborg, suede",
            "jonköping, suede",
            "karlstad, suede",
            "kiruna, suede",
            "linköping, suede",
            "lund, suede",
            "malmö, suede",
            "norrköping, suede",
            "stockholm, suede",
            "sundsvall, suede",
            "södertälje, suede",
            "täby, suede",
            "umeå, suede",
            "uppsala, suede",
            "västerås, suede",
            "växjö, suede",
            "örebro, suede",
            // -------------------------------------
            // DANEMARK
            // -------------------------------------
            "aalborg, danemark",
            "aarhus, danemark",
            "copenhague, danemark",
            "esbjerg, danemark",
            "frederiksberg, danemark",
            "herning, danemark",
            "hilleroed, danemark",
            "holstebro, danemark",
            "horsens, danemark",
            "hørsholm, danemark",
            "kolding, danemark",
            "køge, danemark",
            "næstved, danemark",
            "odense, danemark",
            "randers, danemark",
            "roskilde, danemark",
            "silkeborg, danemark",
            "slagelse, danemark",
            "tårnby, danemark",
            "vejle, danemark",
            "viborg, danemark",
            // -------------------------------------
            // FINLANDE
            // -------------------------------------
            "espoo, finlande",
            "helsinki, finlande",
            "imatra, finlande",
            "joensuu, finlande",
            "jyväskylä, finlande",
            "kajaani, finlande",
            "kotka, finlande",
            "kouvola, finlande",
            "kuopio, finlande",
            "lahti, finlande",
            "lappeenranta, finlande",
            "mikkeli, finlande",
            "oulu, finlande",
            "pori, finlande",
            "rauma, finlande",
            "riihimäki, finlande",
            "rovaniemi, finlande",
            "salo, finlande",
            "savonlinna, finlande",
            "seinaejoki, finlande",
            "tampere, finlande",
            "turku, finlande",
            "vaasa, finlande",
            "vantaa, finlande",
            // -------------------------------------
            // GROENLAND
            // -------------------------------------
            "nuuk, groenland",
            "sisimiut, groenland",
            // -------------------------------------
            // COSTA RICA
            // -------------------------------------
            "alajuela, costa rica",
            "cartago, costa rica",
            "golfito, costa rica",
            "grecia, costa rica",
            "guapiles, costa rica",
            "heredia, costa rica",
            "liberia, costa rica",
            "limon, costa rica",
            "palmares, costa rica",
            "puntarenas, costa rica",
            "quesada, costa rica",
            "san isidro, costa rica",
            "san josé, costa rica",
            "san ramon, costa rica",
            "siquirres, costa rica",
            // -------------------------------------
            // NIGERIA 
            // -------------------------------------
            "aba, nigeria",
            "abuja, nigeria",
            "akure, nigeria",
            "bauchi, nigeria",
            "benin city, nigeria",
            "calabar, nigeria",
            "ebonyi, nigeria",
            "enugu, nigeria",
            "ibadan, nigeria",
            "ilorin, nigeria",
            "jos, nigeria",
            "kaduna, nigeria",
            "kano, nigeria",
            "lagos, nigeria",
            "maiduguri, nigeria",
            "minna, nigeria",
            "owerri, nigeria",
            "port harcourt, nigeria",
            "sokoto, nigeria",
            "warri, nigeria",
            "zaria, nigeria",
            // -------------------------------------
            // PHILIPPINES 
            // -------------------------------------
            "angeles, philippines",
            "antipolo, philippines",
            "bacolod, philippines",
            "baguio, philippines",
            "batangas, philippines",
            "biñan, philippines",
            "cagayan de oro, philippines",
            "caloocan, philippines",
            "cebu, philippines",
            "davao, philippines",
            "iloilo city, philippines",
            "lapu-lapu, philippines",
            "las piñas, philippines",
            "makati, philippines",
            "mandaluyong, philippines",
            "manille, philippines",
            "marikina, philippines",
            "muntinlupa, philippines",
            "parañaque, philippines",
            "pasig, philippines",
            "quezon city, philippines",
            "san jose del monte, philippines",
            "taguig, philippines",
            "zamboanga, philippines",
            // -------------------------------------
            // NOUVELLE-ZELANDE
            // -------------------------------------
            "ashburton, nouvelle-zélande",
            "auckland, nouvelle-zélande",
            "blenheim, nouvelle-zélande",
            "christchurch, nouvelle-zélande",
            "dunedin, nouvelle-zélande",
            "gisborne, nouvelle-zélande",
            "greymouth, nouvelle-zélande",
            "hamilton, nouvelle-zélande",
            "invercargill, nouvelle-zélande",
            "napier-hastings, nouvelle-zélande",
            "nelson, nouvelle-zélande",
            "new plymouth, nouvelle-zélande",
            "palmerston north, nouvelle-zélande",
            "queenstown, nouvelle-zélande",
            "rotorua, nouvelle-zélande",
            "taupo, nouvelle-zélande",
            "tauranga, nouvelle-zélande",
            "timaru, nouvelle-zélande",
            "wanaka, nouvelle-zélande",
            "wellington, nouvelle-zélande",
            "whakatane, nouvelle-zélande",
            "whanganui, nouvelle-zélande",
            "whangarei, nouvelle-zélande",
            // -------------------------------------
            // EGYPTE
            // -------------------------------------
            "alexandrie, égypte",
            "asieut, égypte",
            "beni suef, égypte",
            "el-mahalla el-kubra, égypte",
            "fayoum, égypte",
            "hurghada, égypte",
            "ismaïlia, égypte",
            "le caire, égypte",
            "mansoura, égypte",
            "minya, égypte",
            "port-saïd, égypte",
            "qena, égypte",
            "sharm el-cheikh, égypte",
            "sohag, égypte",
            "suez, égypte",
            "tanta, égypte",
            "zagazig, égypte",
            // -------------------------------------
            // VIETNAM
            // -------------------------------------
            "bac lieu, vietnam",
            "binh duong, vietnam",
            "buon ma thuot, vietnam",
            "can tho, vietnam",
            "da nang, vietnam",
            "dong nai, vietnam",
            "ha tinh, vietnam",
            "hai duong, vietnam",
            "haiphong, vietnam",
            "hanoï, vietnam",
            "ho chi minh-ville, vietnam",
            "hue, vietnam",
            "nha trang, vietnam",
            "phu quoc, vietnam",
            "phu yen, vietnam",
            "quy nhon, vietnam",
            "soc trang, vietnam",
            "thanh hoa, vietnam",
            "vinh, vietnam",
            // -------------------------------------
            // LAOS
            // -------------------------------------
            "attapeu, laos",
            "champasak, laos",
            "luang namtha, laos",
            "luang prabang, laos",
            "pakse, laos",
            "phonsavan, laos",
            "saravane, laos",
            "savannakhet, laos",
            "vientiane, laos",
            // -------------------------------------
            // KENYA
            // -------------------------------------
            "eldoret, kenya",
            "embu, kenya",
            "garissa, kenya",
            "isiolo, kenya",
            "kakamega, kenya",
            "kericho, kenya",
            "kilifi, kenya",
            "kisumu, kenya",
            "kitale, kenya",
            "lamu, kenya",
            "machakos, kenya",
            "malindi, kenya",
            "meru, kenya",
            "migori, kenya",
            "mombasa, kenya",
            "nairobi, kenya",
            "naivasha, kenya",
            "nakuru, kenya",
            "nanyuki, kenya",
            "narok, kenya",
            "nyeri, kenya",
            "thika, kenya",
             // -------------------------------------
            // GUATEMALA
            // -------------------------------------
            "antigua guatemala, guatemala",
            "chimaltenango, guatemala",
            "chiquimula, guatemala",
            "cobán, guatemala",
            "escuintla, guatemala",
            "guatemala city, guatemala",
            "huehuetenango, guatemala",
            "jalapa, guatemala",
            "jutiapa, guatemala",
            "mazatenango, guatemala",
            "mixco, guatemala",
            "petapa, guatemala",
            "puerto barrios, guatemala",
            "quetzaltenango, guatemala",
            "quiché, guatemala",
            "retalhuleu, guatemala",
            "san juan sacatepéquez, guatemala",
            "sololá, guatemala",
            "villa nueva, guatemala",
            "zacapa, guatemala",
            // -------------------------------------
            // CUBA
            // -------------------------------------
            "bayamo, cuba",
            "camagüey, cuba",
            "cardenas, cuba",
            "ciego de ávila, cuba",
            "cienfuegos, cuba",
            "contramaestre, cuba",
            "guantánamo, cuba",
            "holguín, cuba",
            "la havane, cuba",
            "las tunas, cuba",
            "manzanillo, cuba",
            "matanzas, cuba",
            "moa, cuba",
            "morón, cuba",
            "nueva gerona, cuba",
            "palma soriano, cuba",
            "pinar del río, cuba",
            "sancti spíritus, cuba",
            "santa clara, cuba",
            "santiago de cuba, cuba",
            // -------------------------------------
            // VENEZUELA
            // -------------------------------------
            "barcelona, venezuela",
            "barquisimeto, venezuela",
            "cabimas, venezuela",
            "caracas, venezuela",
            "ciudad bolivar, venezuela",
            "ciudad guayana, venezuela",
            "coro, venezuela",
            "cumana, venezuela",
            "guarenas, venezuela",
            "guatire, venezuela",
            "los teques, venezuela",
            "maracaibo, venezuela",
            "maracay, venezuela",
            "maturin, venezuela",
            "merida, venezuela",
            "puerto cabello, venezuela",
            "puerto la cruz, venezuela",
            "punto fijo, venezuela",
            "san cristobal, venezuela",
            "valencia, venezuela",
            // -------------------------------------
            // CHILI
            // -------------------------------------
            "antofagasta, chili",
            "arica, chili",
            "calama, chili",
            "chillan, chili",
            "concepcion, chili",
            "copiapo, chili",
            "coquimbo, chili",
            "iquique, chili",
            "la serena, chili",
            "los angeles, chili",
            "osorno, chili",
            "puerto montt, chili",
            "punta arenas, chili",
            "quillota, chili",
            "rancagua, chili",
            "santiago, chili",
            "talca, chili",
            "temuco, chili",
            "valdivia, chili",
            "valparaiso, chili",
            // -------------------------------------
            // PEROU (autres villes sans données)
            // -------------------------------------
            "lima, pérou",
            "trujillo, pérou",
            // -------------------------------------
            // CROATIE
            // -------------------------------------
            "bjelovar, croatie",
            "dubrovnik, croatie",
            "karlovac, croatie",
            "koprivnica, croatie",
            "krapina, croatie",
            "osijek, croatie",
            "pozega, croatie",
            "pula, croatie",
            "rijeka, croatie",
            "sibenik, croatie",
            "sisak, croatie",
            "slavonski brod, croatie",
            "split, croatie",
            "varazdin, croatie",
            "velika gorica, croatie",
            "vinkovci, croatie",
            "vukovar, croatie",
            "zadar, croatie",
            "zagreb, croatie",
            "zupanja, croatie",
            // -------------------------------------
            // NOUVELLE-CALEDONIE
            // -------------------------------------
            "bourail, nouvelle-calédonie",
            "canala, nouvelle-calédonie",
            "dumbéa, nouvelle-calédonie",
            "houaïlou, nouvelle-calédonie",
            "koné, nouvelle-calédonie",
            "koumac, nouvelle-calédonie",
            "la fôa, nouvelle-calédonie",
            "lifou, nouvelle-calédonie",
            "maré, nouvelle-calédonie",
            "mont-dore, nouvelle-calédonie",
            "nouméa, nouvelle-calédonie",
            "païta, nouvelle-calédonie",
            "poindimié, nouvelle-calédonie",
            "thio, nouvelle-calédonie",
            "yate, nouvelle-calédonie",
            // -------------------------------------
            // FIDJI
            // -------------------------------------
            "ba, fidji",
            "labasa, fidji",
            "lautoka, fidji",
            "nadi, fidji",
            "navua, fidji",
            "rakiraki, fidji",
            "suva, fidji",
            "tavua, fidji",
            // -------------------------------------
            // AUTRICHE
            // -------------------------------------
            "graz, autriche",
            "linz, autriche",
            "salzbourg, autriche",
            "vienne, autriche",
            // -------------------------------------
            // MALI
            // -------------------------------------
            "bamako, mali",
            "sikasso, mali",
            "mopti, mali",
            "koutiala, mali",
            // -------------------------------------
            // SOUDAN
            // -------------------------------------
            "al-qadarif, soudan",
            "al-ubayyid, soudan",
            "bahri, soudan",
            "kassala, soudan",
            "khartoum, soudan",
            "kosti, soudan",
            "nyala, soudan",
            "omdourman, soudan",
            "port-soudan, soudan",
            "wad madani, soudan",
            // -------------------------------------
            // OUGANDA
            // -------------------------------------
            "gulu, ouganda",
            "jinja, ouganda",
            "kampala, ouganda",
            "lira, ouganda",
            // -------------------------------------
            // TANZANIE
            // -------------------------------------
            "dar es salaam, tanzanie",
            "mwanza, tanzanie",
            "zanzibar, tanzanie",
            "arusha, tanzanie",
            "mbeya, tanzanie",
            "morogoro, tanzanie",
            "tanga, tanzanie",
            "dodoma, tanzanie",
            "kigoma, tanzanie",
            "moshi, tanzanie",
            "tabora, tanzanie",
            // -------------------------------------
            // MOZAMBIQUE
            // -------------------------------------
            "maputo, mozambique",
            "matola, mozambique",
            "beira, mozambique",
            "nampula, mozambique",
            "chimoio, mozambique",
            "nacala, mozambique",
            "quelimane, mozambique",
            "mocuba, mozambique",
            "tete, mozambique",
            "xai-xai, mozambique",
            // -------------------------------------
            // ZIMBABWE
            // -------------------------------------
            "harare, zimbabwe",
            "bulawayo, zimbabwe",
            "chitungwiza, zimbabwe",
            "mutare, zimbabwe",
            "gweru, zimbabwe",
            "epworth, zimbabwe",
            // -------------------------------------
            // NAMIBIE
            // -------------------------------------
            "windhoek, namibie",
            "walvis bay, namibie",
            "swakopmund, namibie",
            "ondangwa, namibie",
            // -------------------------------------
            // ANGOLA
            // -------------------------------------
            "luanda, angola",
            "huambo, angola",
            "lobito, angola",
            "benguela, angola",
            "lucapa, angola",
            "lubango, angola",
            // -------------------------------------
            // REPUBLIQUE DU CONGO
            // -------------------------------------
            "brazzaville, république du congo",
            "pointe-noire, république du congo",
            "dolisie, république du congo",
            "nkayui, république du congo",
            "loango, république du congo",
            // -------------------------------------
            // REPUBLIQUE DEMOCRATIQUE DU CONGO
            // -------------------------------------
            "kinshasa, république démocratique du congo",
            "mbujimayi, république démocratique du congo",
            "lubumbashi, république démocratique du congo",
            "kananga, république démocratique du congo",
            "kisangani, république démocratique du congo",
            "goma, république démocratique du congo",
            "bukavu, république démocratique du congo",
            "tshikapa, république démocratique du congo",
            "kolwezi, république démocratique du congo",
            "likasi, république démocratique du congo",
            "kikwit, république démocratique du congo",
            "uvira, république démocratique du congo",
            "bunia, république démocratique du congo",
            "kalemie, république démocratique du congo",
            "mbandaka, république démocratique du congo",
            "matadi, république démocratique du congo",
            "kadinda, république démocratique du congo",
            // -------------------------------------
            // REPUBLIQUE CENTRAFRICAINE 
            // -------------------------------------
            "bangui, république centrafricaine",
            "bimbo, république centrafricaine",
            "berbérati, république centrafricaine",
            "carnot, république centrafricaine",
            "balbari, république centrafricaine",
            // -------------------------------------
            // SOUDAN DU SUD
            // -------------------------------------
            "djouba, soudan du sud",
            "wau, soudan du sud",
            "malakal, soudan du sud",
            "yei, soudan du sud",
            "yambio, soudan du sud",
            // -------------------------------------
            // TCHAD
            // -------------------------------------
            "n'djaména, tchad",
            "moundou, tchad",
            "abeche, tchad",
            "sarh, tchad",
            // -------------------------------------
            // IRAN
            // -------------------------------------
            "téhéran, iran",
            "ispahan, iran",
            "tabriz, iran",
            "karadj, iran",
            "chiraz, iran",
            "ahvaz, iran",
            "kermanchah, iran",
            "zahedan, iran",
            "racht, iran",
            "kerman, iran",
            "hamadan, iran",
            "arak, iran",
            "yazd, iran",
            "ardabil, iran",
            "bandar abbas, iran",
            // -------------------------------------
            // IRAK
            // -------------------------------------
            "bagdad, irak",
            "bassorah, irak",
            "mossoul, irak",
            "arbil, irak",
            "souleimaniye, irak",
            "kirkuk, irak",
            "kerbela, irak",
            "nassiriya, irak",
            "amara, irak",
            "diwaniya, irak",
            "kut, irak",
            "hilla, irak",
            "ramadi, irak",
            "tall afar, irak",
            // -------------------------------------
            // TURQUIE
            // -------------------------------------
            "istanbul, turquie",
            "ankara, turquie",
            "izmir, turquie",
            "bursa, turquie",
            "adana, turquie",
            "gaziantep, turquie",
            "konya, turquie",
            "antalya, turquie",
            "kayseri, turquie",
            "mersin, turquie",
            "diyarbakır, turquie",
            "eskişehir, turquie",
            "denizli, turquie",
            "sanlıurfa, turquie",
            "samsun, turquie",
            "malatya, turquie",
            "adapazarı, turquie",
            "kahramanmaraş, turquie",
            "esenyurt, turquie",
            "erzurum, turquie",
            "van, turquie",
            "elâzığ, turquie",
            "batman, turquie",
            "izmit, turquie",
            "sivas, turquie",
            "sultanbeyli, turquie",
            "manisa, turquie",
            "gebze, turquie",
            "balıkesir, turquie",
            "tarsus, turquie",
            "sancaktepe, turquie",
            // -------------------------------------
            // SYRIE
            // -------------------------------------
            "alep, syrie",
            "damas, syrie",
            "homs, syrie",
            "lattaquié, syrie",
            "hama, syrie",
            "al-hasaka, syrie",
            "tartous, syrie",
            "duma, syrie",
            // -------------------------------------
            // PAKISTAN
            // -------------------------------------
            "karachi, pakistan",
            "lahore, pakistan",
            "faisalabad, pakistan",
            "rawalpindi, pakistan",
            "gujranwala, pakistan",
            "peshawar, pakistan",
            "multan, pakistan",
            "hyderabad, pakistan",
            "islamabad, pakistan",
            "quetta, pakistan",
            "bahawalpur, pakistan",
            "sargodha, pakistan",
            "sialkot, pakistan",
            "sukkur, pakistan",
            "larkana, pakistan",
            "shekhupura, pakistan",
            "rahim yar khan, pakistan",
            "jhang, pakistan",
            // -------------------------------------
            // AFGHANISTAN
            // -------------------------------------
            "kaboul, afghanistan",
            "hérat, afghanistan",
            "kandahâr, afghanistan",
            "mazar-e-charif, afghanistan",
            "jalalabad, afghanistan",
            "kondôz, afghanistan",
            // -------------------------------------
            // BANGLADESH
            // -------------------------------------
            "dhaka, bangladesh",
            "chittagong, bangladesh",
            "khulna, bangladesh",
            "râjshâhî, bangladesh",
            "sylhet, bangladesh",
            "tongi, bangladesh",
            "rangpur, bangladesh",
            "narayanganj, bangladesh",
            "maimansingh, bangladesh",
            "barisal, bangladesh",
            // -------------------------------------
            // BIRMANIE
            // -------------------------------------
            // "rangoon, myanmar",  UNABLE TO RETRIEVE DATA FROM Visual Crossing (BAD REQUEST)
            "mandalay, myanmar",
            "naypyidaw, myanmar",
            "bago, myanmar",
            // -------------------------------------
            // CAMBODGE
            // -------------------------------------
            "phnom penh, cambodge",
            "sihanoukville, cambodge",
            "battambang, cambodge",
            "siem reap, cambodge",
            // -------------------------------------
            // URUGUAY
            // -------------------------------------
            "montevideo, uruguay",
            "salto, uruguay",
            "paysandu, uruguay",
            "maldonado, uruguay",
            // -------------------------------------
            // PARAGUAY
            // -------------------------------------
            "asuncion, paraguay",
            "ciudad del este, paraguay",
            "san lorenzo, paraguay",
            "luque, paraguay",
            "capiatá, paraguay",
            "lambaré, paraguay",
            "fernando de la mora, paraguay",
            "limpio, paraguay",
            "ñemby, paraguay",
            // -------------------------------------
            // BOLIVIE
            // -------------------------------------
            "santa cruz de la sierra, bolivie",
            "el alto, bolivie",
            "la paz, bolivie",
            "cochabamba, bolivie",
            "oruro, bolivie",
            "sucre, bolivie",
            "tarija, bolivie",
            "potosí, bolivie",
            "sacaba, bolivie",
            "quillacollo, bolivie",
            "montero, bolivie",
            "trinidad, bolivie",
            "yacuiba, bolivie",
            // -------------------------------------
            // EQUATEUR
            // -------------------------------------
            "guayaquil, équateur",
            "quito, équateur",
            "cuenca, équateur",
            "santo domingo, équateur",
            "machala, équateur",
            "durán, équateur",
            "portoviejo, équateur",
            "manta, équateur",
            "loja, équateur",
            "ambato, équateur",
            // -------------------------------------
            // GUYANE FRANÇAISE
            // -------------------------------------
            "Cayenne, guyane française",
            "Kourou, guyane française",
            "Matoury, guyane française",
            // -------------------------------------
            // PANAMA
            // -------------------------------------
            "panama, panama",
            "san miguelito, panama",
            "tocumen, panama",
            // -------------------------------------
            // NICARAGUA
            // -------------------------------------
            "managua, nicaragua",
            "león, nicaragua",
            "chinandega, nicaragua",
            "masaya, nicaragua",
            "estelí, nicaragua",
            // -------------------------------------
            // HONDURAS
            // -------------------------------------
            "tegucigalpa, honduras",
            "san pedro sula, honduras",
            "choloma, honduras",
            "la ceiba, honduras",
            "el progreso, honduras",
            "choluteca, honduras",
            "comayagua, honduras",
            // -------------------------------------
            // SALVADOR
            // -------------------------------------
            "san salvador, salvador",
            "soyapango, salvador",
            "santa ana, salvador",
            "san miguel, salvador",
            "mejicanos, salvador",
            "apopa, salvador",
            "delgado, salvador",
            "santa tecla, salvador",
            "ilopango, salvador",
            // -------------------------------------
            // TADJIKISTAN
            // -------------------------------------*
            "douchanbé, tadjikistan",
            "kulob, tadjikistan",
            // -------------------------------------
            // KIRGHIZISTAN
            // -------------------------------------
            "bichkek, kirghizistan",
            "och, kirghizistan",
            "jalal-abad, kirghizistan",
            // -------------------------------------
            // KAZAKHSTAN
            // -------------------------------------
            "almaty, kazakhstan",
            "astana, kazakhstan",
            "chimkent, kazakhstan",
            "karaganda, kazakhstan",
            "aktioubé, kazakhstan",
            "pavlodar, kazakhstan",
            "taraz, kazakhstan",
            "semeï, kazakhstan",
            "öskemen, kazakhstan",
            // -------------------------------------
            // GÉORGIE
            // -------------------------------------
            "tbilissi, géorgie",
            "batoumi, géorgie",
            "koutaïssi, géorgie",
            "roustavi, géorgie",
            "gori, géorgie",
            // -------------------------------------
            // ARMÉNIE
            // -------------------------------------
            "yerevan, arméni",
            "gyumri, arméni",
            "vanadzor, arméni",
            // -------------------------------------
            // AZERBAÏDJAN
            // -------------------------------------
            "bakou, azerbaïdjan",
            "gandja, azerbaïdjan",
            "sumqayıt, azerbaïdjan",
            "mingachevir, azerbaïdjan",
            // -------------------------------------
            // TURKMÉNISTAN
            // -------------------------------------
            "achgabat, turkménistan",
            "türkmenabat, turkménistan",
            "daşoguz, turkménistan",
            "mary, turkménistan",
            // -------------------------------------
            // OUZBÉKISTAN
            // -------------------------------------
            "tachkent, ouzbékistan",
            "samarcande, ouzbékistan",
            "namangan, ouzbékistan",
            "andijan, ouzbékistan",
            "boukhara, ouzbékistan",
            "karchi, ouzbékistan",
            "kokand, ouzbékistan",
            "ferghana, ouzbékistan",
            "termez, ouzbékistan",
            "navoï, ouzbékistan",
            "angren, ouzbékistan",
            // -------------------------------------
            // BIÉLORUSSIE
            // -------------------------------------
            "minsk, biélorussie",
            "homiel, biélorussie",
            "mahiliow, biélorussie",
            "vitebsk, biélorussie",
            "hrodna, biélorussie",
            "brest, biélorussie",
            "babrouïsk, biélorussie",
            "baranavitchy, biélorussie",
            "baryssaw, biélorussie",
            "pinsk, biélorussie",
            "orcha, biélorussie",
            "mazyr, biélorussie",
            "salihorsk, biélorussie",
            "navapolatsk, biélorussie",
            "lida, biélorussie",
            // -------------------------------------
            // LITUANIE
            // -------------------------------------
            "vilnius, lituanie",
            "kaunas, lituanie",
            "klaipėda, lituanie",
            "šiauliai, lituanie",
            "panevėžys, lituanie",
            // -------------------------------------
            // LETTONIE
            // -------------------------------------
            "riga, lettonie",
            "daugavpils, lettonie",
            "liepāja, lettonie",
            // -------------------------------------
            // ESTONIE
            // -------------------------------------
            "tallinn, estonie",
            "narva, estonie",
            "pärnu, estonie",
            "tartu, estonie",
            "rae, estonie",
            // -------------------------------------
            // JORDANIE
            // -------------------------------------
            "amman, jordanie",
            "zarqa, jordanie",
            "irbid, jordanie",
            "wadi as-sir, jordanie",
            // -------------------------------------
            // CHYPRE
            // -------------------------------------
            "nicosie, chypre",
            "limassol, chypre",
            "stróvolos, chypre",
            // -------------------------------------
            // LIBAN
            // -------------------------------------
            "beyrouth, liban",
            "tripoli, liban",
            "sidon, liban",
            "nabatieh, liban",
            // -------------------------------------
            // KOWEÏT
            // -------------------------------------
            "hawalli, koweït",
            "mubarak al-kabeer, koweït",
            "koweït, koweït",
            // -------------------------------------
            // ÉMIRATS ARABES UNIS
            // -------------------------------------
            "dubaï1, émirats arabes unis",
            "abou dabi, émirats arabes unis",
            "charjah, émirats arabes unis",
            "ras el-khaïmah, émirats arabes unis",
            "al ain, émirats arabes unis",
            "ajman, émirats arabes unis",
            // -------------------------------------
            // SOMALIE
            // -------------------------------------
            "mogadiscio, somalie",
            "hargeisa, somalie",
            "borama, somalie",
            "merka, somalie",
            "kismaayo, somalie",
            "jamaame, somalie",
            "burao, somalie",
            // -------------------------------------
            // ZAMBIE
            // -------------------------------------
            "lusaka, zambie",
            "ndola, zambie",
            "kitwe, zambie",
            "kabwe, zambie",
            "chingola, zambie",
            "mufulira, zambie",
            "livingstone, zambie",
            "luanshya, zambie",
            // -------------------------------------
            // RWANDA
            // -------------------------------------
            "kigali, rwanda",
            "butare, rwanda",
            "gitarama, rwanda",
            "byumba, rwanda",
            "cyangugu, rwanda",
            "kibungo, rwanda",
            // -------------------------------------
            // BURUNDI
            // -------------------------------------
            "bujumbura, burundi",
            "gitega, burundi",
            "ngozi, burundi",
            "rumonge, burundi",
            // -------------------------------------
            // MONACO
            // -------------------------------------
            "monaco, monaco",
            // -------------------------------------
            // PAPOUASIE-NOUVELLE-GUINÉE
            // -------------------------------------
            "port moresby, papouasie-nouvelle-guinée",
            "lae, papouasie-nouvelle-guinée",
            // -------------------------------------
            // GHANA
            // -------------------------------------
            "accra, ghana",
            "kumasi, ghana",
            "tamale, ghana",
            "sekondi-takoradi, ghana",
            "ashaiman, ghana",
            "sunyani, ghana",
            "cape coast, ghana",
            "obuasi, ghana",
            "teshie, ghana",
            "tema, ghana",
            "madina, ghana",
            "koforidua, ghana",
            "wa, ghana",
            // -------------------------------------
            // MONGOLIE
            // -------------------------------------
            "oulan-bator, mongolie",
            "darkhan, mongolie",
            "erdenet, mongolie",
            // -------------------------------------
            // RÉPUBLIQUE DOMINICAINE
            // -------------------------------------
            "saint-domingue, république dominicaine",
            "santiago de los caballeros, république dominicaine",
            "san pedro de macorís, république dominicaine",
            "la romana, république dominicaine",
            "los alcarrizos, république dominicaine",
            "san cristóbal, république dominicaine",
            "higüey, république dominicaine",
            "san francisco de macorís, république dominicaine",
            "puerto plata, république dominicaine",
            "concepción de la vega, république dominicaine",
            "santa cruz de barahona, république dominicaine",
            // -------------------------------------
            // GUADELOUPE
            // -------------------------------------
            "pointe-à-pitre, guadeloupe",
            // -------------------------------------
            // MARTINIQUE
            // -------------------------------------
            "fort-de-france, martinique",
         };

    }
}
