namespace VisualCrossingDataGrabber.Services
{
    internal static class Locations
    {
        public static string[] All = new string[] {
            // -------------------------------------
            // FRANCE
            // -------------------------------------
            "agde, france",
            "aix-en-provence, france",
            "ajaccio, france",
            "amiens, france",
            "agen, france",
            "angers, france",
            "annecy, france",
            "antibes, france",
            "arras, france",
            "aurillac, france",
            "avignon, france",
            "bayonne, france",
            "bergerac, france",
            "belfort, france",
            "besançon, france",
            "béziers, france",
            "biarritz, france",
            "bordeau, france",
            "bordeaux, france",
            "bourges, france",
            "brest, france",
            "briançon, france",
            "brive-la-gaillarde, france",
            "caen, france",
            "calais, france",
            "cannes, france",
            "castres, france",
            "chambéry, france",
            "champagnole, france",
            "châteauroux, france",
            "clermont-ferrand, france",
            "colmar, france",
            "courchevel, france",
            "foix, france",
            "forbach, france",
            "digoin, france",
            "dijon, france",
            "dunkerque, france",
            "fort-de-france, france",
            "gap, france",
            "grenoble, france",
            "isola, france",
            "la rochelle, france",
            "laruns, france",
            "le havre, france",
            "le mans , france",
            "le puy-en-vela, france",
            "lembach, france",
            "les abymes, france",
            "les menuires, france",
            "les Sables-d'Olonne, france",
            "lille, france",
            "limoges, france",
            "lourdes, france",
            "lyon, france",
            "marseille, france",
            "mérignac, france",
            "metz, france",
            "mont-de-marsan, france",
            "montélimar, france",
            "montpellier, france",
            "mouthe, france",
            "mulhouse, france",
            "nancy, france",
            "nantes, france",
            "narbonne, france",
            "nevers, france",
            "nice, france",
            "nîmes, france",
            "nouméa, france",
            "orleans, france",
            "paray-le-monial, france",
            "paris, france",
            "pau, france",
            "périgueux, france",
            "perpignan, france",
            "poitiers, france",
            "pontarlier, france",
            "quimper, france",
            "reins, france",
            "rennes, france",
            "roubaix, france",
            "rouen, france",
            "saint-étienne, france",
            "saint-jean-de-maurienne, france",
            "saint-nazaire, france",
            "saint-pierre, france",
            "saint-tropez, france",
            "strasbourg, france",
            "toulon, france",
            "toulouse, france",
            "tourcoing, france",
            "tournus, france",
            "tours, france",
            "troyes, france",
            "val thorens, france",
            "valence, france",
            "versailles, france",
            "vichy, france",
            // -------------------------------------
            // ESPAGNE ; jusqu'à 40 depuis https://fr.wikipedia.org/wiki/Liste_de_villes_d%27Espagne
            // + quelques villes
            // -------------------------------------
            "albacete, espagne",
            "alcalá de henares, espagne",
            "alcorcón, espagne",
            "alicante, espagne",
            "almeria, espagne",
            "almeria, espagne",
            "avila, espagne",
            "badajoz, espagne",
            "badalone, espagne",
            "barcelone, espagne",
            "bilbao, espagne",
            "burgos, espagne",
            "caceres, espagne",
            "cadix, espagne",
            "carthagène, espagne",
            "castellon, espagne",
            "castellón de la plana, espagne",
            "ciudad real, espagne",
            "cordoue, espagne",
            "cuenca, espagne",
            "elche, espagne",
            "fuenlabrada, espagne",
            "getafe, espagne",
            "gijón, espagne",
            "grenade, espagne",
            "guadalajara, espagne",
            "huelva, espagne",
            "huesca, espagne",
            "jaen, espagne",
            "jerez de la frontera, espagne",
            "l'hospitalet de llobregat, espagne",
            "la corogne, espagne",
            "las palmas de gran canaria, espagne",
            "leganés, espagne",
            "leon, espagne",
            "logroño, espagne",
            "lugo, espagne",
            "léon, espagne",
            "lérida, espagne",
            "madrid, espagne",
            "malaga, espagne",
            "murcie, espagne",
            "móstoles, espagne",
            "orense, espagne",
            "oviedo, espagne",
            "palma de majorque, espagne",
            "pampelune, espagne",
            "pontevedra, espagne",
            "sabadell, espagne",
            "saint-sébastien, espagne",
            "salamanque, espagne",
            "santa cruz de tenerife, espagne",
            "santander, espagne",
            "saragosse, espagne",
            "segovie, espagne",
            "soria, espagne",
            "séville, espagne",
            "tarragone, espagne",
            "terrassa, espagne",
            "tolede, espagne",
            "valence, espagne",
            "valladolid, espagne",
            "vigo, espagne",
            "vitoria-gasteiz, espagne",
            "zamora, espagne",
            // -------------------------------------
            // ITALIE ; jusqu'à 44 depuis https://fr.wikipedia.org/wiki/Liste_des_villes_d%27Italie_par_nombre_d%27habitants
            // + quelques autres.
            // -------------------------------------
            "ancone, italie",
            "arezzo, italie",
            "asti, italie",
            "bari, italie",
            "benevento, italie",
            "bergame, italie",
            "bologne, italie",
            "bolzane, italie",
            "brescia, italie",
            "brindisi, italie",
            "cagliari, italie",
            "campobasso, italie",
            "caserte, italie",
            "catane, italie",
            "catanzaro, italie",
            "chieti, italie",
            "cosenza, italie",
            "cremona, italie",
            "côme, italie",
            "ferrare, italie",
            "florence, italie",
            "foggia, italie",
            "forlì, italie",
            "frosinone, italie",
            "giugliano in campania, italie",
            "grosseto, italie",
            "gênes, italie",
            "l'aquila, italie",
            "la spezia, italie",
            "latina, italie",
            "lecce, italie",
            "livourne, italie",
            "lodi, italie",
            "lucca, italie",
            "massa, italie",
            "matera, italie",
            "messine, italie",
            "milan, italie",
            "modène, italie",
            "monza, italie",
            "naples, italie",
            "novare, italie",
            "olbia, italie",
            "oristano, italie",
            "padoue, italie",
            "palermo, italie",
            "parme, italie",
            "pavia, italie",
            "pescara, italie",
            "piacenza, italie",
            "pise, italie",
            "plaisance, italie",
            "potenza, italie",
            "prato, italie",
            "pérouse, italie",
            "ravenna, italie",
            "ravenne, italie",
            "reggio d'émilie, italie",
            "reggio de calabre, italie",
            "rieti, italie",
            "rimini, italie",
            "rome, italie",
            "saint-marin, italie",
            "salerne, italie",
            "sassari, italie",
            "sienne, italie",
            "siracusa, italie",
            "sondrio, italie",
            "syracuse, italie",
            "taranto, italie",
            "tarente, italie",
            "terni, italie",
            "trente, italie",
            "trieste, italie",
            "turin, italie",
            "udine, italie",
            "varese, italie",
            "venezia, italie",
            "venise, italie",
            "vercelli, italie",
            "vicence, italie",
            "viterbo, italie",
            "vérone, italie",
            // -------------------------------------
            // ALLEMAGNE ; jusqu'à 48 depuis https://fr.wikipedia.org/wiki/Liste_des_plus_grandes_villes_d%27Allemagne
            // -------------------------------------
            "aix-la-chapelle, allemagne",
            "augsbourg, allemagne",
            "bayreuth, allemagne",
            "berlin, allemagne",
            "bielefeld, allemagne",
            "bochum, allemagne",
            "bonn, allemagne",
            "bremen, allemagne",
            "brunswick, allemagne",
            "brême, allemagne",
            "cassel, allemagne",
            "chemnitz, allemagne",
            "cobourg, allemagne",
            "cologne, allemagne",
            "constance, allemagne",
            "cottbus, allemagne",
            "darmstadt, allemagne",
            "dortmund, allemagne",
            "dresde, allemagne",
            "duisbourg, allemagne",
            "düsseldorf, allemagne",
            "erfurt, allemagne",
            "essen, allemagne",
            "flensbourg, allemagne",
            "francfort, allemagne",
            "freiburg, allemagne",
            "fribourg-en-brisgau, allemagne",
            "gelsenkirchen, allemagne",
            "gotha, allemagne",
            "hagen, allemagne",
            "halle, allemagne",
            "hambourg, allemagne",
            "hamm, allemagne",
            "hanovre, allemagne",
            "heidelberg, allemagne",
            "heilbronn, allemagne",
            "ingolstadt, allemagne",
            "jena, allemagne",
            "kaiserslautern, allemagne",
            "karlsruhe, allemagne",
            "kiel, allemagne",
            "krefeld, allemagne",
            "leipzig, allemagne",
            "leverkusen, allemagne",
            "ludwigshafen, allemagne",
            "lübeck, allemagne",
            "magdebourg, allemagne",
            "mannheim, allemagne",
            "mayence, allemagne",
            "munich, allemagne",
            "mönchengladbach, allemagne",
            "mülheim, allemagne",
            "münster, allemagne",
            "nuremberg, allemagne",
            "oberhausen, allemagne",
            "offenbach, allemagne",
            "oldenbourg, allemagne",
            "osnabrück, allemagne",
            "passau, allemagne",
            "potsdam, allemagne",
            "regensburg, allemagne",
            "reutlingen, allemagne",
            "rostock, allemagne",
            "sarrebruck, allemagne",
            "schwerin, allemagne",
            "siegen, allemagne",
            "stuttgart, allemagne",
            "trier, allemagne",
            "ulm, allemagne",
            "weimar, allemagne",
            "wiesbaden, allemagne",
            "wolfsburg, allemagne",
            "worms, allemagne",
            "wuppertal, allemagne",
            "zwickau, allemagne",
            // -------------------------------------
            // SUISSE ; jusqu'à 15 depuis https://fr.wikipedia.org/wiki/Liste_des_villes_de_Suisse
            // -------------------------------------
            "aigle, suisse",
            "bellinzone, suisse",
            "berne, suisse",
            "bienne, suisse",
            "bâle, suisse",
            "chur, suisse",
            "davos, suisse",
            "delémont, suisse",
            "frauenfeld, suisse",
            "fribourg, suisse",
            "genève, suisse",
            "glaris, suisse",
            "granges, suisse",
            "interlaken, suisse",
            "köniz, suisse",
            "lausanne, suisse",
            "locarno, suisse",
            "lucerne, suisse",
            "lugano, suisse",
            "martigny, suisse",
            "montreux, suisse",
            "morat, suisse",
            "neuchâtel, suisse",
            "olten, suisse",
            "saint-gall, suisse",
            "schaan, suisse",
            "schaffhouse, suisse",
            "sion, suisse",
            "soleure, suisse",
            "thoune, suisse",
            "uster, suisse",
            "vevey, suisse",
            "winterthour, suisse",
            "yverdon-les-bains, suisse",
            "zoug, suisse",
            "zurich, suisse",
            // -------------------------------------
            // BELGIQUE ; jusqu'à 21 depuis https://fr.wikipedia.org/wiki/Liste_des_communes_de_Belgique_par_population
            // -------------------------------------
            "alost, belgique",
            "anderlecht, belgique",
            "anvers, belgique",
            "arlon, belgique",
            "bruges, belgique",
            "bruxelles, belgique",
            "charleroi, belgique",
            "courtrai, belgique",
            "dinant, belgique",
            "gand, belgique",
            "genk, belgique",
            "hasselt, belgique",
            "herstal, belgique",
            "ixelles, belgique",
            "la louvière, belgique",
            "laeken, belgique",
            "leuven, belgique",
            "liège, belgique",
            "louvain, belgique",
            "malines, belgique",
            "molenbeek-saint-jean, belgique",
            "mons, belgique",
            "namur, belgique",
            "nivelles, belgique",
            "ostende, belgique",
            "roeselare, belgique",
            "saint-nicolas, belgique",
            "schaerbeek, belgique",
            "seraing, belgique",
            "tournai, belgique",
            "uccle, belgique",
            "verviers, belgique",
            "villers-la-ville, belgique",
            "waregem, belgique",
            "wavre, belgique",
            "yprès, belgique",
            "zaventem, belgique",
            // -------------------------------------
            // USA ; jusqu'à 36 depuis https://fr.wikipedia.org/wiki/Liste_des_villes_les_plus_peupl%C3%A9es_des_%C3%89tats-Unis
            // -------------------------------------
            "albuquerque, usa",
            "anchorage, usa",
            "arlington, usa",
            "atlanta, usa",
            "aurora, usa",
            "austin, usa",
            "bakersfield, usa",
            "baltimore, usa",
            "birmingham, usa",
            "boise, usa",
            "boston, usa",
            "buffalo, usa",
            "charlotte, usa",
            "chattanooga, usa",
            "chicago, usa",
            "cleveland, usa",
            "colorado springs, usa",
            "columbus, usa",
            "corpus christi, usa",
            "dallas, usa",
            "daytona beach, usa",
            "denver, usa",
            "des moines, usa",
            "détroit, usa",
            "el paso, usa",
            "fargo, usa",
            "fort lauderdale, usa",
            "fort worth, usa",
            "fresno, usa",
            "grand rapids, usa",
            "green bay, usa",
            "honolulu, usa",
            "houston, usa",
            "indianapolis, usa",
            "jacksonville, usa",
            "kansas city, usa",
            "knoxville, usa",
            "la nouvelle-orléans, usa",
            "las vegas, usa",
            "lincoln, usa",
            "long beach, usa",
            "los angeles, usa",
            "louisville, usa",
            "lubbock, usa",
            "madison, usa",
            "memphis, usa",
            "mesa, usa",
            "miami, usa",
            "milwaukee, usa",
            "minneapolis, usa",
            "mobile, usa",
            "nashville, usa",
            "new york, usa",
            "oakland, usa",
            "oklahoma city, usa",
            "omaha, usa",
            "orlando, usa",
            "philadelphie, usa",
            "phoenix, usa",
            "pittsburgh, usa",
            "portland, usa",
            "raleigh, usa",
            "reno, usa",
            "richmond, usa",
            "rochester, usa",
            "sacramento, usa",
            "saint louis, usa",
            "salt lake city, usa",
            "san antonio, usa",
            "san diego, usa",
            "san francisco, usa",
            "san josé, usa",
            "sarasota, usa",
            "seattle, usa",
            "spokane, usa",
            "springfield, usa",
            "syracuse, usa",
            "tampa, usa",
            "tucson, usa",
            "tulsa, usa",
            "virginia beach, usa",
            "washington DC, usa",
            "wichita, usa",
            // -------------------------------------
            // Bresil ; jusqu'à 8 depuis https://fr.wikipedia.org/wiki/Liste_de_villes_du_Br%C3%A9sil
            // -------------------------------------
            "anápolis, brésil",
            "aracaju, brésil",
            "belo horizonte, brésil",
            "belém, brésil",
            "betim, brésil",
            "brasília, brésil",
            "campinas, brésil",
            "campo grande, brésil",
            "contagem, brésil",
            "curitiba, brésil",
            "duque de caxias, brésil",
            "feira de santana, brésil",
            "fortaleza, brésil",
            "goiânia, brésil",
            "guarulhos, brésil",
            "jaboatão dos guararapes, brésil",
            "joinville, brésil",
            "joão pessoa, brésil",
            "juiz de fora, brésil",
            "londrina, brésil",
            "maceió, brésil",
            "manaus, brésil",
            "natal, brésil",
            "niterói, brésil",
            "nova iguaçu, brésil",
            "osasco, brésil",
            "porto alegre, brésil",
            "recife, brésil",
            "ribeirão preto, brésil",
            "rio de janeiro, brésil",
            "salvador da bahia, brésil",
            "santo andré, brésil",
            "sorocaba, brésil",
            "são bernardo do campo, brésil",
            "são gonçalo, brésil",
            "são josé dos campos, brésil",
            "são luís, brésil",
            "são paulo, brésil",
            "teresina, brésil",
            "uberlândia, brésil",
            // -------------------------------------
            // Japon ; jusqu'à 18 depuis https://fr.wikipedia.org/wiki/Liste_des_villes_du_Japon_par_nombre_d%27habitants
            // -------------------------------------
            "akita, japon",
            "chiba, japon",
            "fukuoka, japon",
            "funabashi, japon",
            "hamamatsu, japon",
            "himeji, japon",
            "hiroshima, japon",
            "kagoshima, japon",
            "kanazawa, japon",
            "kawasaki, japon",
            "kitakyūshū, japon",
            "koriyama, japon",
            "kumamoto, japon",
            "kyōto, japon",
            "kōbe, japon",
            "kōchi, japon",
            "matsumoto, japon",
            "miyazaki, japon",
            "nagasaki, japon",
            "nagoya, japon",
            "naha, japon",
            "nara, japon",
            "niigata, japon",
            "ochiai, japon",
            "okayama, japon",
            "saitama, japon",
            "sakai, japon",
            "sapporo, japon",
            "sendai, japon",
            "shizuoka, japon",
            "takamatsu, japon",
            "tokyo, japon",
            "toyama, japon",
            "utsunomiya, japon",
            "wakayama, japon",
            "yamagata, japon",
            "yokohama, japon",
            "ōsaka, japon",
            // -------------------------------------
            // Australie ; jusqu'à 10 depuis https://fr.wikipedia.org/wiki/Liste_des_villes_d%27Australie_par_nombre_d%27habitants
            // -------------------------------------
            "adélaïde, australie",
            "albury, australie",
            "ballarat, australie",
            "bathurst, australie",
            "bendigo, australie",
            "brisbane, australie",
            "bunbury, australie",
            "bundaberg, australie",
            "cairns, australie",
            "canberra, australie",
            "coffs harbour, australie",
            "darwin, australie",
            "dubbo, australie",
            "geelong, australie",
            "geraldton, australie",
            "gladstone, australie",
            "gold coast, australie",
            "hervey bay, australie",
            "hobart, australie",
            "kalgoorlie, australie",
            "launceston, australie",
            "mackay, australie",
            "melbourne, australie",
            "mildura, australie",
            "newcastle, australie",
            "orange, australie",
            "perth, australie",
            "port macquarie, australie",
            "rockhampton, australie",
            "shepparton, australie",
            "sunshine coast, australie",
            "sydney, australie",
            "tamworth, australie",
            "toowoomba, australie",
            "townsville, australie",
            "wagga wagga, australie",
            "wollongong, australie",
            // -------------------------------------
            // CANADA ; jusqu'à 14 depuis https://fr.wikipedia.org/wiki/Villes_du_Canada_par_population
            // -------------------------------------
            "abbotsford, canada",
            "ajax, canada",
            "barrie, canada",
            "brampton, canada",
            "burlington, canada",
            "burnaby, canada",
            "calgary, canada",
            "cambridge, canada",
            "coquitlam, canada",
            "delta, canada",
            "edmonton, canada",
            "gatineau, canada",
            "greater sudbury, canada",
            "guelph, canada",
            "halifax, canada",
            "hamilton, canada",
            "kelowna, canada",
            "kingston, canada",
            "kitchener, canada",
            "langley, canada",
            "laval, canada",
            "london, canada",
            "longueuil, canada",
            "lévis, canada",
            "markham, canada",
            "milton, canada",
            "mississauga, canada",
            "montréal, canada",
            "oakville, canada",
            "oshawa, canada",
            "ottawa, canada",
            "québec, canada",
            "regina, canada",
            "richmond hill, canada",
            "richmond, canada",
            "saanich, canada",
            "saguenay, canada",
            "saskatoon, canada",
            "sherbrooke, canada",
            "st. catharines, canada",
            "st. john's, canada",
            "surrey, canada",
            "terrebonne, canada",
            "thunder bay, canada",
            "toronto, canada",
            "trois-rivières, canada",
            "vancouver, canada",
            "vaughan, canada",
            "waterloo, canada",
            "whitby, canada",
            "winnipeg, canada",
            // -------------------------------------
            // POLOGNE ; jusqu'à 15 depuis https://fr.wikipedia.org/wiki/Liste_des_plus_grandes_villes_de_Pologne
            // -------------------------------------
            "białystok, pologne",
            "bielsko-biała, pologne",
            "bydgoszcz, pologne",
            "bytom, pologne",
            "chorzów, pologne",
            "cracovie, pologne",
            "częstochowa, pologne",
            "elbląg, pologne",
            "gdańsk, pologne",
            "gdynia, pologne",
            "gliwice, pologne",
            "jelenia góra, pologne",
            "kalisz, pologne",
            "katowice, pologne",
            "kielce, pologne",
            "koszalin, pologne",
            "legnica, pologne",
            "lublin, pologne",
            "malbork, pologne",
            "nowy sącz, pologne",
            "olsztyn, pologne",
            "opole, pologne",
            "poznań, pologne",
            "płock, pologne",
            "radom, pologne",
            "ruda śląska, pologne",
            "rybnik, pologne",
            "rzeszów, pologne",
            "sosnowiec, pologne",
            "szczecin, pologne",
            "tarnów, pologne",
            "toruń, pologne",
            "varsovie, pologne",
            "wrocław, pologne",
            "zabrze, pologne",
            "zielona góra, pologne",
            "łódź, pologne",
            "śląsk, pologne",
            // -------------------------------------
            // AFRIQUE DU SUD ; jusqu'à 12 depuis https://fr.wikipedia.org/wiki/Liste_de_villes_d%27Afrique_du_Sud
            // -------------------------------------
            "benoni, afrique du sud",
            "bloemfontein, afrique du sud",
            "boksburg, afrique du sud",
            "durban, afrique du sud",
            "east london, afrique du sud",
            "george, afrique du sud",
            "grahamstown, afrique du sud",
            "johannesburg, afrique du sud",
            "kimberley, afrique du sud",
            "knysna, afrique du sud",
            "krugersdorp, afrique du sud",
            "le cap, afrique du sud",
            "mahikeng, afrique du sud",
            "nelspruit, afrique du sud",
            "oudtshoorn, afrique du sud",
            "paarl, afrique du sud",
            "pietermaritzburg, afrique du sud",
            "polokwane, afrique du sud",
            "port elizabeth, afrique du sud",
            "pretoria, afrique du sud",
            "randburg, afrique du sud",
            "rustenburg, afrique du sud",
            "soweto, afrique du sud",
            "springs, afrique du sud",
            "stellenbosch, afrique du sud",
            "tembisa, afrique du sud",
            "ulundi, afrique du sud",
            "upington, afrique du sud",
            "vereeniging, afrique du sud",
            "welkom, afrique du sud",
            // -------------------------------------
            // NORVEGE ; depuis https://fr.wikipedia.org/wiki/Liste_de_villes_de_Norv%C3%A8ge
            // -------------------------------------
            "arendal, norvège",
            "askøy, norvège",
            "bergen, norvège",
            "bodø, norvège",
            "drammen, norvège",
            "fredrikstad, norvège",
            "gjøvik, norvège",
            "halden, norvège",
            "hamar, norvège",
            "harstad, norvège",
            "haugesund, norvège",
            "horten, norvège",
            "kongsberg, norvège",
            "kristiansand, norvège",
            "kristiansund, norvège",
            "larvik, norvège",
            "lillehammer, norvège",
            "mo i rana, norvège",
            "molde, norvège",
            "moss, norvège",
            "oslo, norvège",
            "porsgrunn, norvège",
            "sandefjord, norvège",
            "sandvika, norvège",
            "sarpsborg, norvège",
            "skien, norvège",
            "stavanger, norvège",
            "tromsø, norvège",
            "trondheim, norvège",
            "tønsberg, norvège",
            "ålesund, norvège",
            // -------------------------------------
            // SINGAPOUR ; 
            // -------------------------------------
            "singapour, singapour",
            // -------------------------------------
            // HAWAÏ ; 
            // -------------------------------------
            "hilo, hawaï",
            "honolulu, hawaï",
            "kahului, maui",
            "kailua-kona, hawaï",
            "lahaina, maui",
            "lihue, kauai",
            "waimea, kauai",
            // -------------------------------------
            // MEXIQUE ; 
            // -------------------------------------
            "aguascalientes, mexique",
            "chihuahua, mexique",
            "ciudad victoria, mexique",
            "culiacán, mexique",
            "durango, mexique",
            "ecatepec, mexique",
            "guadalajara, mexique",
            "hermosillo, mexique",
            "irapuato, mexique",
            "juárez, mexique",
            "león, mexique",
            "mexicali, mexique",
            "mexico, mexique",
            "monterrey, mexique",
            "morelia, mexique",
            "mérida, mexique",
            "naucalpan, mexique",
            "nezahualcóyotl, mexique",
            "puebla, mexique",
            "querétaro, mexique",
            "reynosa, mexique",
            "saltillo, mexique",
            "san luis potosí, mexique",
            "tijuana, mexique",
            "tlaquepaque, mexique",
            "torreón, mexique",
            "tuxtla gutiérrez, mexique",
            "tuxtla, mexique",
            "veracruz, mexique",
            "villahermosa, mexique",
            "xalapa, mexique",
            "zapopan, mexique",
            // -------------------------------------
            // COLOMBIE ; 
            // -------------------------------------
            "armenia, colombie",
            "barranquilla, colombie",
            "bello, colombie",
            "bogota, colombie",
            "bucaramanga, colombie",
            "buenaventura, colombie",
            "cali, colombie",
            "cartagena, colombie",
            "cartago, colombie",
            "cúcuta, colombie",
            "dosquebradas, colombie",
            "envigado, colombie",
            "floridablanca, colombie",
            "ibagué, colombie",
            "manizales, colombie",
            "medellín, colombie",
            "montería, colombie",
            "neiva, colombie",
            "palmira, colombie",
            "pasto, colombie",
            "pereira, colombie",
            "popayán, colombie",
            "santa marta, colombie",
            "sincelejo, colombie",
            "soacha, colombie",
            "soledad, colombie",
            "tulúa, colombie",
            "valledupar, colombie",
            "villavicencio, colombie",
            // -------------------------------------
            // ARGENTINE ; depuis https://fr.wikipedia.org/wiki/Liste_de_villes_d%27Argentine
            // -------------------------------------
            "bahía blanca, argentine",
            "buenos aires, argentine",
            "catamarca, argentine",
            "corrientes, argentine",
            "córdoba, argentine",
            "formosa, argentine",
            "la plata, argentine",
            "la rioja, argentine",
            "mar del plata, argentine",
            "mendoza, argentine",
            "neuquén, argentine",
            "paraná, argentine",
            "posadas, argentine",
            "rawson, argentine",
            "resistencia, argentine",
            "rosario, argentine",
            "río gallegos, argentine",
            "salta, argentine",
            "san juan, argentine",
            "san luis, argentine",
            "san miguel de tucumán, argentine",
            "san salvador de jujuy, argentine",
            "santa fe, argentine",
            "santiago del estero, argentine",
            "tucumán, argentine",
            "ushuaia, argentine",
            // -------------------------------------
            // ALGERIE ; depuis https://fr.wikipedia.org/wiki/Liste_de_villes_d%27Alg%C3%A9rie
            // -------------------------------------
            "ain defla, algérie",
            "alger, algérie",
            "annaba, algérie",
            "batna, algérie",
            "biskra, algérie",
            "bjelfa, algérie",
            "blida, algérie",
            "bordj bou arreridj, algérie",
            "béjaïa, algérie",
            "chlef, algérie",
            "constantine, algérie",
            "el eulma, algérie",
            "el oued, algérie",
            "guelma, algérie",
            "jijel, algérie",
            "khénchela, algérie",
            "laghouat, algérie",
            "mascara, algérie",
            "mostaganem, algérie",
            "médéa, algérie",
            "oran, algérie",
            "ouargla, algérie",
            "sidi bel abbès, algérie",
            "skikda, algérie",
            "souk ahras, algérie",
            "sétif, algérie",
            "tiaret, algérie",
            "tizi ouzou, algérie",
            "tlemcen, algérie",
            "tébessa, algérie",
            // -------------------------------------
            // MAROC ; depuis https://fr.wikipedia.org/wiki/Liste_des_grandes_villes_du_Maroc_par_population
            // -------------------------------------
            "agadir, maroc",
            "al hoceima, maroc",
            "beni mellal, maroc",
            "berrechid, maroc",
            "bouskoura, maroc",
            "casablanca, maroc",
            "dakhla, maroc",
            "el jadida, maroc",
            "errachidia, maroc",
            "essaouira, maroc",
            "fès, maroc",
            "guelmim, maroc",
            "kenitra, maroc",
            "khouribga, maroc",
            "khémisset, maroc",
            "larache, maroc",
            "marrakech, maroc",
            "martil, maroc",
            "meknès, maroc",
            "ouarzazate, maroc",
            "oujda, maroc",
            "rabat, maroc",
            "safi, maroc",
            "salé, maroc",
            "settat, maroc",
            "tanger, maroc",
            "taourirt, maroc",
            "taroudant, maroc",
            "tetouan, maroc",
            "tiznit, maroc",
            "témara, maroc",
            // -------------------------------------
            // ARABIE SAOUDITE ; depuis https://fr.wikipedia.org/wiki/Liste_des_grandes_villes_du_Maroc_par_population
            // -------------------------------------
            "abha, arabie saoudite",
            "al hufuf, arabie saoudite",
            "al khobar, arabie saoudite",
            "al mubarraz, arabie saoudite",
            "al qatif, arabie saoudite",
            "buraidah, arabie saoudite",
            "dammam, arabie saoudite",
            "djeddah, arabie saoudite",
            "ha'il, arabie saoudite",
            "jizan, arabie saoudite",
            "jubail, arabie saoudite",
            "khamis mushait, arabie saoudite",
            "khobar, arabie saoudite",
            "la mecque, arabie saoudite",
            "médine, arabie saoudite",
            "najran, arabie saoudite",
            "riyad, arabie saoudite",
            "ta'if, arabie saoudite",
            "tabuk, arabie saoudite",
            "yanbu, arabie saoudite",
            // -------------------------------------
            // CHINE ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_de_Chine_par_nombre_d%27habitants
            // -------------------------------------
            "changsha, chine",
            "changzhou, chine",
            "chengdu, chine",
            "chongqing, chine",
            "dalian, chine",
            "dongguan, chine",
            "fuzhou, chine",
            "guangzhou, chine",
            "guiyang, chine",
            "haikou, chine",
            "hangzhou, chine",
            "harbin, chine",
            "huzhou, chine",
            "jinan, chine",
            "kunming, chine",
            "lanzhou, chine",
            "luoyang, chine",
            "nanchang, chine",
            "nanjing, chine",
            "nanning, chine",
            "ningbo, chine",
            "pékin, chine",
            "qingdao, chine",
            "shanghai, chine",
            "shenyang, chine",
            "shenzhen, chine",
            "suzhou, chine",
            "tianjin, chine",
            "urumqi, chine",
            "wuhan, chine",
            "wuxi, chine",
            "xi'an, chine",
            "xiamen, chine",
            "xining, chine",
            "yinchuan, chine",
            "zhengzhou, chine",
            // -------------------------------------
            // INDE ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_d%27Inde
            // -------------------------------------
            "agra, inde",
            "ahmedabad, inde",
            "allahabad, inde",
            "amritsar, inde",
            "bengaluru, inde",
            "bhopal, inde",
            "chandigarh, inde",
            "chennai, inde",
            "coimbatore, inde",
            "delhi, inde",
            "dhanbad, inde",
            "faridabad, inde",
            "firozabad, inde",
            "guwahati, inde",
            "gwalior, inde",
            "hubli–dharwad, inde",
            "hyderabad, inde",
            "indore, inde",
            "jabalpur, inde",
            "jaipur, inde",
            "jodhpur, inde",
            "kanpur, inde",
            "kolkata, inde",
            "lucknow, inde",
            "ludhiana, inde",
            "madurai, inde",
            "meerut, inde",
            "mumbai, inde",
            "nagpur, inde",
            "nashik, inde",
            "patna, inde",
            "pune, inde",
            "raipur, inde",
            "rajpur sonarpur, inde",
            "srinagar, inde",
            "surat, inde",
            "thane, inde",
            "vadodara, inde",
            "varanasi, inde",
            "vijayawada, inde",
            "visakhapatnam, inde",
            // -------------------------------------
            // ROYAUME-UNI ; depuis https://fr.wikipedia.org/wiki/Liste_de_villes_du_Royaume-Uni
            // -------------------------------------
            "aberdeen, royaume-uni",
            "bath, royaume-uni",
            "belfast, royaume-uni",
            "birmingham, royaume-uni",
            "bradford, royaume-uni",
            "brighton, royaume-uni",
            "bristol, royaume-uni",
            "cambridge, royaume-uni",
            "cardiff, royaume-uni",
            "coventry, royaume-uni",
            "derby, royaume-uni",
            "dundee, royaume-uni",
            "exeter, royaume-uni",
            "glasgow, royaume-uni",
            "inverness, royaume-uni",
            "kingston, royaume-uni",
            "lancaster, royaume-uni",
            "leeds, royaume-uni",
            "leicester, royaume-uni",
            "liverpool, royaume-uni",
            "londres, royaume-uni",
            "manchester, royaume-uni",
            "newcastle, royaume-uni",
            "norwich, royaume-uni",
            "nottingham, royaume-uni",
            "oxford, royaume-uni",
            "peterborough, royaume-uni",
            "plymouth, royaume-uni",
            "portsmouth, royaume-uni",
            "sheffield, royaume-uni",
            "southampton, royaume-uni",
            "stoke-on-trent, royaume-uni",
            "sunderland, royaume-uni",
            "swansea, royaume-uni",
            "wolverhampton, royaume-uni",
            "york, royaume-uni",
            "édimbourg, royaume-uni",
            // -------------------------------------
            // IRLANDE ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_de_l%27%C3%89tat_d%27Irlande
            // -------------------------------------
            "athlone, irlande",
            "bray, irlande",
            "carlow, irlande",
            "cork, irlande",
            "drogheda, irlande",
            "dublin, irlande",
            "dundalk, irlande",
            "ennis, irlande",
            "galway, irlande",
            "kilkenny, irlande",
            "killarney, irlande",
            "letterkenny, irlande",
            "limerick, irlande",
            "naas, irlande",
            "navan, irlande",
            "sligo, irlande",
            "sword, irlande",
            "tralee, irlande",
            "waterford, irlande",
            // -------------------------------------
            // ISLAND ; depuis https://fr.wikipedia.org/wiki/Liste_des_localit%C3%A9s_d%27Islande
            // -------------------------------------
            "akranes, islande",
            "akureyri, islande",
            "borgarnes, islande",
            "egilsstaðir, islande",
            "garðabær, islande",
            "hafnarfjörður, islande",
            "húsavík, islande",
            "keflavík, islande",
            "kópavogur, islande",
            "mosfellsbær, islande",
            "neskaupstaður, islande",
            "reykjavik, islande",
            "sauðárkrókur, islande",
            "selfoss, islande",
            "siglufjörður, islande",
            "ísafjörður, islande",
            // -------------------------------------
            // MADAGASCAR ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_de_Madagascar
            // -------------------------------------
            "tananarive, madagascar",
            // -------------------------------------
            // PORTUGAL ; depuis https://herald-dick-magazine.blogspot.com/2015/06/top-10-des-plus-grandes-villes-du.html
            // -------------------------------------
            "lisbonne, portugal",
            "porto, portugal",
            "vila nova de gaia, portugal",
            "amadora, portugal",
            // -------------------------------------
            // PAYS-BAS ; depuis 
            // -------------------------------------
            "amsterdam, pays-bas",
            "la haye, pays-bas",
            "rotterdam, pays-bas",
            // -------------------------------------
            // GRECE ; depuis https://fr.wikipedia.org/wiki/Liste_de_villes_de_Gr%C3%A8ce
            // -------------------------------------
            "athènes, grèce",
            "thessalonique, grèce",
            "patras, grèce",
            "larissa, grèce",
            // -------------------------------------
            // TUNISIE ; depuis 
            // -------------------------------------
            "tunis, tunisie",
            "sfax, tunisie",
            "sousse, tunisie",
            "kairouan, tunisie",
            "bizerte, tunisie",
            // -------------------------------------
            // MALTE ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_de_Malte
            // -------------------------------------
            "birkirkara, malte",
            "il-mosta, malte",
            // -------------------------------------
            // ISRAËL ; depuis https://fr.wikipedia.org/wiki/Liste_des_villes_d%27Isra%C3%ABl
            // -------------------------------------
            "jérusalem, israël",
            "tel aviv, israël",
            "haïfa, israël",
            "rishon lezion, israël",
            "holon, israël",
            // -------------------------------------
            // COREE DU SUD ; depuis 
            // -------------------------------------
            "séoul, corée du sud",
            "busan, corée du sud",
            "incheon, corée du sud",
            // -------------------------------------
            // NEPAL ; depuis 
            // -------------------------------------
            "katmandou, népal",
            // -------------------------------------
            // RUSSIE ; depuis 
            // -------------------------------------
            "moscou, russie",
            "saint-pétersbourg, russie",
            "novossibirsk, russie",
            "iekaterinbourg, russie",
            "nijni novgorod, russie",
            "kazan, russie",
            "samara, russie",
            "tcheliabinsk, russie",
            "omsk, russie",
            // -------------------------------------
            // TCHEQUIE; depuis 
            // -------------------------------------
            "prague, tchéquie",
            "brno, tchéquie",
            // -------------------------------------
            // SLOVAQUIE; depuis 
            // -------------------------------------
            "bratislava, slovaquie",
            // -------------------------------------
            // ROUMANIE; depuis 
            // -------------------------------------
            "bucarest, roumanie",
            "cluj, roumanie",
            "constanta, roumanie",
            "timisoara, roumanie",
            // -------------------------------------
            // HONGRIE; depuis 
            // -------------------------------------
            "budapest, hongrie",
            // -------------------------------------
            // MOLDAVIE; depuis 
            // -------------------------------------
            "chisinau, moldavie",
            // -------------------------------------
            // UKRAINE; depuis 
            // -------------------------------------
            "kiev, ukraine",
            "kharkiv, ukraine",
            "odessa, ukraine",
            "dnipro, ukraine",
            "donetsk, ukraine",
            // -------------------------------------
            // SUEDE; depuis 
            // -------------------------------------
            "stockholm, suede",
            "göteborg, suede",
            "kiruna, suede",
            // -------------------------------------
            // DANEMARK; depuis 
            // -------------------------------------
            "copenhague, danemark",
            "aarhus, danemark",
            "odense, danemark",
            // -------------------------------------
            // FINLANDE; depuis 
            // -------------------------------------
            "helsinki, finlande",
            "oulu, finlande",
            "tampere, finlande",
            "rovaniemi, finlande",
            // -------------------------------------
            // GROENLAND; depuis 
            // -------------------------------------
            "nuuk, groenland",
            // -------------------------------------
            // COSTA RICA; depuis 
            // -------------------------------------
            "san josé, costa rica",
            // -------------------------------------
            // NIGERIA; depuis 
            // -------------------------------------
            "abuja, nigeria",
            // -------------------------------------
            // PHILIPPINES; depuis 
            // -------------------------------------
            "quezon city, philippines",
            "manille, philippines",
            "davao, philippines",
            "caloocan, philippines",
            // -------------------------------------
            // NOUVELLE-ZELANDE; depuis https://destination-nouvellezelande.com/villes-incontournables-nouvelle-zelande/
            // -------------------------------------
            "auckland, nouvelle-zélande",
            "christchurch, nouvelle-zélande",
            "wellington, nouvelle-zélande",
            "nelson, nouvelle-zélande",
            "dunedin, nouvelle-zélande",
        };

    }
}
